### ISSUE TITLE
Reduce characteristic categories to store ontology annotations instead of material attributes

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#103]
In the study_schema.json, the property characteristicCategories stores objects defined by material_attribute_schema.json. In material_attribute_schema.json, we have one propertythat points to an ontology annotation. This seems redundant since this is synonymous with using an ontology annotation directly (which is what unitCategories does).

I propose to modify study_schema.json so the characteristicCategories items reference ontology_annotation_schema.json directly, unless there is any reason to keep it how it is?

**Comment by agbeltran** [comment]
Discussed in meeting. Agreed that structurally, we can remove material_attribute_schema.json and just use ontology_annotation_schema.json (as in unitCategories).

In terms of semantics, when we consider JSON-LD, it seems that it would be possible to annotate the items (without needed the extra schema).

"If an array is at the top-level of the referencing document and its items are JSON objects, the @context subtree is added to all array items." (from https://www.w3.org/TR/json-ld/)
