### ISSUE TITLE
ISA-JSON visualisation or validation?

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#107]
Could you recommend a validator for ISA-JSON? Also are there scripts to visualise ISA-JSON, similar to https://github.com/ISA-tools/ISATab-Viewer or http://scientificdata.isa-explorer.org/ ?

We are looking to validate/visualise the ISA-JSON [generated from a database](https://apps.ideaconsult.net/enanomapper/bundle/1/substance?media=application%2Fisa%2Bjson&max=3)

**Comment by proccaserra** [comment]
@vedina we are about to release an alpha version of a new validator in about 2 week time. @djcomlab leads the development on that side.
I had a look at the json you pointed to and was wondering about the first process sequence. Should it be part of the assay ? I mean that the assay process sequence should have a 'executes protocol' element in it.
Have you check the conversion to ISA-Tab and is it satisfactory?

**Comment by vedina** [comment]
Not yet checked, part of my question was what's do you recommend to start with for validation?

**Comment by proccaserra** [comment]
Right now, a good test would be to run the conversions from json to tab for a quick visual inspection until we have the python based validator is released. Furthermore, you could still use the java based one on the converted ISA-Tab file to checked the syntax. My gut feeling looking at the json is that while it looks syntactically fine, the underlying data may be missing clarity to distinguish between 'sample preparation' (a process sequence, with ideally a pointer to a protocol) and 'data acquisition' (the assay with a process sequence, again, ideally pointing to a specific protocol)

**Comment by djcomlab** [comment]
Hi @vedina I've just pushed a new validator for ISA-JSON into the master branch of the repo, although we've only really tested it with our own test data so may need further work. But it would be great if you could try it out.

**Comment by vedina** [comment]
Sorry for the late reply. @djcomlab do you have any help how to run the validator ?

**Comment by proccaserra** [comment]
@vedina 

from isatools import isatab
from isatools.model.v1 import *

isatab.validate2(open('temp/i_investigation.txt'),'./isaconfig-default_v2015-07-02/')

**Comment by ntk73** [comment]
We managed to run the conversions isatab <--> son (in both directions).
I would like to ask: are all json keywords obligatory to be present in the json file even when they are empty?

**Comment by djcomlab** [comment]
Hiya Nikolai, currently anything that reads ISA JSON (so the ISA JSON validator and the json2xxxxx converters) usually requires some key-values to be present even if empty.

But we ideally hope to make the converters more resilient to empty values being omitted completely to make it cleaner.
