### ISSUE TITLE
Represent configuration files in the JSON rep for ISA v1

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#11]

**Comment by agbeltran** [comment]
Investigate if this representation is needed, or just deal with the XML for the moment.

**Comment by djcomlab** [comment]
Having been working with the configs the last few days, we can now read them into Python objects to use. A JSON representation is not needed.

**Comment by agbeltran** [comment]
We decided to leave this issue to be investigated for future releases, as it might become useful when considering JSON-LD representation/ ISA extensions/etc. For now, we can rely on the XML configuration files.

**Comment by djcomlab** [comment]
These were done as part of JSON validator work (in isatools/config/json), in master since 0.2 release. Closing.
