### ISSUE TITLE
rst file improperly rendered in github

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#117]
#python code blocks are not visible , (same in readthedoc of course)

**Comment by djcomlab** [comment]
Hi @proccaserra can you be more specific when reporting an issue? e.g. What include what file(s) exactly.

As far as I understand the rst's in the API repo are not supposed for rendering on Github, but on readthedocs.org

**Comment by djcomlab** [comment]
For reference: http://sqa.stackexchange.com/questions/1920/best-guidelines-for-bug-reporting

"Nothing can ruin your day like a poorly-written bug report." 😂

**Comment by proccaserra** [comment]
@djcomlab 

![image](https://cloud.githubusercontent.com/assets/517736/16616478/62a32610-4375-11e6-9268-fa7495e75899.png)

not rendered in readthedoc either. 

see after 'do something like the following:' on the following page http://isatools.readthedocs.io/en/latest/validation.html

"nothing can ruin your day like pedantism "  😂 😂

**Comment by djcomlab** [comment]
That's more like it!

**Comment by djcomlab** [comment]
Fixed in master. Thank you for the report.

Have a nice day. 👯
