### ISSUE TITLE
SampleTab export

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#120]
Create converter for export to SampleTab (https://www.ebi.ac.uk/biosamples/help/st.html)

**Comment by agbeltran** [comment]
NCBI validator service: https://www.ncbi.nlm.nih.gov/biosample/docs/submission/validation-service/

**Comment by proccaserra** [comment]
similarly, from EBI:
https://www.ebi.ac.uk/biosamples/sampletab/validation.html

Tony Burdett got back to me with examples from different projects, showing how to code specific situations -> to be reviewed
