### ISSUE TITLE
Batch validation generating a report.

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#121]
Add functionality for validating a batch of ISA files (initially Tab, but also JSON). Use for batch validation of Metabolights datasets and SciData datasets

**Comment by djcomlab** [comment]
For the ISA-Tab batch validator, my thinking is that this should need the list of paths to the ISA-Tab directories. We could have the validator write a report out into each ISA-Tab directory with a user-defined report file name, something like: 
```
tab_dir_list = ['path/to/BII-I-1', 'path/to/BII-S-3', 'path/to/BII-S-7']
isatab.batch_validate(tab_dir_list, report_file_name='isatab_report.txt')
```
and we could do something similar for the ISA-JSON batch validator: 
```
json_list = ['path/to/BII-I-1.json', 'path/to/BII-S-3.json', 'path/to/BII-S-7.json']
isajson.batch_validate(json_list, report_file_name='isajson_report.txt')
```

**Comment by djcomlab** [comment]
Probably makes more sense to write the reports out to a single report file, rather than distributing them where the ISA-Tabs or ISA-JSONs sit.

**Comment by djcomlab** [comment]
Build passing, closing.
