### ISSUE TITLE
Conversion to MAGE-TAB

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#124]
Implement conversion to MAGE-TAB for submissions, for example to ArrayExpress.

See https://www.ebi.ac.uk/arrayexpress/submit/overview.html and https://wiki.nci.nih.gov/display/TCGA/MAGE-TAB

**Comment by djcomlab** [comment]
See also: https://github.com/ISA-tools/ISAvalidator-ISAconverter-BIImanager/blob/master/import_layer/src/main/java/org/isatools/isatab/export/magetab/MAGETABExporter.java

**Comment by agbeltran** [comment]
Also check https://www.ebi.ac.uk/arrayexpress/submit/overview.html
and 
 https://www.ebi.ac.uk/fg/annotare/
