### ISSUE TITLE
Allow to specify/parametrize i_investigation.txt file name

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#128]
Currently, fixed valued for the investigation file is used, see:
https://github.com/ISA-tools/isa-api/blob/master/isatools/isatab.py

at line 122:
if os.path.exists(output_path):
        fp = open(os.path.join(output_path, 'i_investigation.txt'), 'w')
    else:
        raise FileNotFoundError("Can't find " + output_path)
## 

investigation_file_name = "i_" + $user_input + "_investigation.txt"

**Comment by djcomlab** [comment]
Added enhancement and build passing, closing.
