### ISSUE TITLE
json2sra conversion produces unpredictable output on BII-S-3

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#129]
I've been wrestling with writing appropriate tests for the SRA conversion (`json2sra), and found that the Java SRA converter does not always output the same XMLs with the same input.

I've been running the SRA converter with BII-S-3, and on some runs the attribute `existing_study_type` in the `study.xml` file of the SRA output is set to `"Other"` rather and in some other runs it is set to `"Transcriptome Analysis"`.

This may be a bug in the SRA converter, but might also be in the `json2isatab` part of the conversion pipeline.

**Comment by proccaserra** [comment]
I am wondering if this is related the order in which the converter would invoke the SRA converter, starting either the genomics or the transcriptomics assay (as BII-S-3 has 2 assay types). as SRA study type accepts only one value (AFAIK) , this may be the cause of the problem.

**Comment by djcomlab** [comment]
Ah yes that might be it, thanks! I'll have a look for this.

**Comment by djcomlab** [comment]
So, the SRA converter still writes out XML for samples and files for both assay types anyway, is that correct? It looks like it includes everything. But I guess if there's more than one assay type it and only accepts one, it can't resolve that particular value perhaps.

**Comment by djcomlab** [comment]
Look like you're right @proccaserra - if I change the other BII-S-3 assay's `measurementType` from `"metagenome sequencing"` to `"transcription profiling"`, the behaviour stays consistent. So this must be a bug in the Java SRA code.

**Comment by proccaserra** [comment]
from SRA 1.5 study xsd:
ftp://ftp.sra.ebi.ac.uk/meta/xsd/sra_1_5/SRA.study.xsd:

<xs:element name="STUDY_TYPE" maxOccurs="1" minOccurs="1">
<xs:annotation>
<xs:documentation>
The STUDY_TYPE presents a controlled vocabulary for expressing the overall purpose of the study.
</xs:documentation>
</xs:annotation>
<xs:complexType>

#not_ideal ! what are users supposed to do when their study has 2 or 3 assay types (RNA-Seq, Chip-Seq,Targeted Gene survey) -> submit 3 distinct studies, and lose of the relation between samples and libraries ?

**Comment by proccaserra** [comment]
could use 'other' or 'new_study_type' with value 'multiomics'

'<xs:attribute name="new_study_type" use="optional" type="xs:string">
<xs:annotation>
<xs:documentation>
To propose a new term, select Other and enter a new study type.
</xs:documentation>
</xs:annotation>
</xs:attribute>

**Comment by djcomlab** [comment]
Is it worth asking the SRA guys for guidance on this, as they would be the ones receiving the submissions?

**Comment by djcomlab** [comment]
To quote info from ENA datasubs "Study type should be ignored. This field is contained in the legacy ERP study".

And actually also` study.xml` should be replaced with a `project_set.xml` that does not store any study type anyway.

**Comment by djcomlab** [comment]
Fix pushed to develop, closing.
