### ISSUE TITLE
Make isa-api distributable

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#14]
Make the API distributable for other developers to use. See https://docs.python.org/2.7//distutils/index.html

**Comment by djcomlab** [comment]
Used distutils to test this. Easy peasy.

https://pypi.python.org/pypi/isatools_api

**Comment by djcomlab** [comment]
This issue was closed back in October? If it's to make the ISA-API 0.1 release distributable, I would think a new ticket should be filed rather than reopening tickets from the past.

**Comment by agbeltran** [comment]
as discussed already, this was not to re-open the ticket :)
