### ISSUE TITLE
Compile/Build failure due to EBI Maven repo 500 error?

### ISSUE THREAD

**Issue by jcmatese** [ISA-tools/isa-api#141]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.112 s
[INFO] Finished at: 2016-08-31T14:55:56-04:00
[INFO] Final Memory: 16M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ISAcreator: Could not resolve dependencies for project org.isatools:ISAcreator:bundle:1.7.9: Failed to collect dependencies at org.isatools:import_layer:jar:1.6.8 -> org.isatools:graph2tab:jar:4.1: Failed to read artifact descriptor for org.isatools:graph2tab:jar:4.1: Could not transfer artifact org.isatools:graph2tab:pom:4.1 from/to ebi-repo (http://www.ebi.ac.uk/~maven/m2repo): Failed to transfer file: http://www.ebi.ac.uk/~maven/m2repo/org/isatools/graph2tab/4.1/graph2tab-4.1.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]

**Comment by jcmatese** [comment]
FYI: reported the issue to the EBI, and a kind soul replied "... one of our data centers ... doing scheduled maintenance on all the servers and storage system ... originally scheduled to be completed yesterday afternoon, but unfortunately they ran into some technical difficulties. ...in the dark about when services are fully restored."

**Comment by agbeltran** [comment]
Thanks @jcmatese, I was going to indicate that I have seen messages from EBI about their data centre. 

Also, this issue is related to the ISAcreator tool (repository here: http://github.com/ISA-tools/ISAcreator) rather than the ISA-API. 

So, I will close this issue now. Many thanks for your feedback.
