### ISSUE TITLE
TypeError indicating missing positional argument for isatab2json.convert

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#144]
Using isatools v0.3.1, `isatab2json.convert(isa_dir)` throws a TypeError.
`TypeError: convert() missing 1 required positional argument: 'json_dir'`

My [recent commit](https://github.com/ISA-tools/isa-api/commit/4c4763dad3a6817d80fde9865dc43cd8200a338a) could have fixed this, as this method documentation is the only remaining appearance of json_dir. Need to test before closing.

**Comment by djcomlab** [comment]
Hiya, I don't believe this is an error in isatools v0.3.1 package. I cannot reproduce this in a fresh virtual environment, and the package on PyPI does not contain any code that would throw this particular TypeError.

The commit you refer to would have no effect as it is only a correction on the docstring, not the method itself.

Please check your local copy of isatools (perhaps try a `pip install isatools --upgrade`).

**Comment by djcomlab** [comment]
Hi @agbeltran did you manage to double-check this? I could not reproduce what you reported.

**Comment by agbeltran** [comment]
I'm not getting this error anymore with v.0.3.4.
