### ISSUE TITLE
Should geographic values have units?

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#154]
In reworking the `model.v1` code, I broke one of the tests in `json2isatab` that uses BII-S-3.json concerning characteristics recording geographic coordinates.

I added a constraint that in `OntologyAnnotation` the term considered should always be a string. However BII-S-3 in the ISA-Tab, and therefore the ISA-JSON, encodes `Characteristics[geographic location (longitude)` and `Characteristics[geographic location (latitude)` as an Ontology Annotation, but with numeric values for the corresponding coordinates.

Should this instead be expressed as a numeric value with a unit, rather than an Ontology Annotation?

i.e. instead of:

| Characteristics[geographic location (longitude)] | Term Source REF | Term Accession Number |
| --- | --- | --- |
| 60.269444 |  |  |

it should be 

| Characteristics[geographic location (longitude)] | Unit | Term Source REF | Term Accession Number |
| --- | --- | --- | --- |
| 60.269444 | Degree |  |  |

**Comment by proccaserra** [comment]
@djcomlab you are right, bug in BII-S-3 representation.

**Comment by djcomlab** [comment]
Also found an instance 

![image](https://cloud.githubusercontent.com/assets/3604134/19475302/45050a58-952b-11e6-910b-378cc341d806.png)

in same study file. Any idea what Unit should go with Fluorescence in this context?

**Comment by proccaserra** [comment]
fluorescence is unitless afair or some kind of arbitrary unit making reporting them is bit moot. 
One question: if we force fields with numeric values to have unit, we may run into issues if people use coding (e.g Male =1  and Female=2) so we may to be flexible

**Comment by djcomlab** [comment]
So I think numeric values can optionally have a Unit - so in the case where they don't have a Unit (and no Unit column), they still can't be Ontology Annotations (i.e. a numeric can't be a term). Will that make sense?

**Comment by proccaserra** [comment]
It does. but it may break older files generated manually. might be worth having a test so that if value is numeric and Ontology annotations fields are present but empty, the validator does not necessarily fails but throws a warning?

**Comment by djcomlab** [comment]
OK cool, I'll test it out.

So actually this isn't something that comes up with the validator right now, but rather that I'm adding constraints now on the model objects, which in-turn starts breaking the conversion tests that use the model objects because of these quirks in the data!

**Comment by agbeltran** [comment]
To consider the case that @proccaserra mentioned above (e.g Male =1 and Female=2), we did allow the ontology annotations to be numeric or strings (see annotationValue in https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/core/ontology_annotation_schema.json) 

So, the constraint "that in `OntologyAnnotation` the term considered should always be a string. " should not be there.

But I agree that there is a bug in BII-S-3, where `geographic location (latitude and longitude) ` should be numeric (and not an OntologyAnnotation), have numeric values and thus, a Unit column associated with it.

**Comment by djcomlab** [comment]
OK, but in the case where 1 and 2 are then considered terms, shouldn't they be coded as "1" and "2" since they are not quantitative? Or are we saying numeric values are not always quantitative? If the latter, then in the specification then we need to make sure explicitly that there is a difference between a numeric and a quantitative value as I think this is quite confusing.

Also, in terms of validation, does that mean we can have mixed types for the term part of an ontology annotation (some values as numerics, some as string, in the same column)?

**Comment by agbeltran** [comment]
I'm OK with considering numeric values always quantitative as agree it is simpler than having to check the particular situations. This implies a change in the ontology_annotation_schema. I would think that change should not impact much. When we did the schema, we discussed this situation but I am not aware of specific datasets being coded with numeric values for ontology annotations.

**Comment by agbeltran** [comment]
This issue is about fixing BII-S-3 (both TAB and JSON) to include a Unit column for 'Characteristic[geographic location (longitude)'  and double-check that tests still work.

**Comment by djcomlab** [comment]
Fixed by https://github.com/ISA-tools/ISAdatasets/issues/1
