### ISSUE TITLE
ISA validator2: sticky error messages with carry over from distinct studies

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#162]
isatools 0.3.4, python 3.5
I am observing in the following:
first invocation of the python validator on CEA-sacurine dataset:
>>> isatab.validate2(open('/Users/Philippe/Documents/PhenoMenal/CEA-Data/isa_sacurine/i_sacurine.txt'), '/Users/Philippe/Documents/git/Configuration-Files/isaconfig-default_v2015-07-02')

second invocation of the python validation on UB-flux dataset:
 isatab.validate2(open('/Users/Philippe/Documents/PhenoMenal/Barcelona-Flux/submitted_study/i_UB_Anusha_HUVEC_hypoxia_vs_normoxia_28jul16.txt'), '/Users/Philippe/Documents/git/Configuration-Files/isaconfig-default_v2015-07-02')

The terminal shows:
>>> isatab.validate2(open('/Users/Philippe/Documents/PhenoMenal/Barcelona-Flux/submitted_study/i_UB_Anusha_HUVEC_hypoxia_vs_normoxia_28jul16.txt'), '/Users/Philippe/Documents/git/Configuration-Files/isaconfig-default_v2015-07-02')
2016-11-17 17:16:08,597 INFO: ISA tab Validator from ISA tools API v0.3
2016-11-17 17:16:08,598 INFO: Loading... /Users/Philippe/Documents/PhenoMenal/Barcelona-Flux/submitted_study/i_UB_Anusha_HUVEC_hypoxia_vs_normoxia_28jul16.txt
2016-11-17 17:16:08,598 INFO: Loading ONTOLOGY SOURCE REFERENCE section
2016-11-17 17:16:08,604 INFO: Loading INVESTIGATION section
2016-11-17 17:16:08,608 INFO: Loading INVESTIGATION PUBLICATIONS section
2016-11-17 17:16:08,613 INFO: Loading INVESTIGATION CONTACTS section
2016-11-17 17:16:08,620 INFO: Loading STUDY section
2016-11-17 17:16:08,627 INFO: Loading STUDY DESIGN DESCRIPTORS section
2016-11-17 17:16:08,632 INFO: Loading STUDY PUBLICATIONS section
2016-11-17 17:16:08,638 INFO: Loading STUDY FACTORS section
2016-11-17 17:16:08,645 INFO: Loading STUDY ASSAYS section
2016-11-17 17:16:08,649 INFO: Loading STUDY PROTOCOLS section
2016-11-17 17:16:08,654 INFO: Loading STUDY CONTACTS section
2016-11-17 17:16:08,659 INFO: Running prechecks...
{'validation_finished': True, 'errors': [{'message': 'Unknown/System Error', 'code': 0, 'supplemental': "The validator could not identify what the error is: 'utf-8' codec can't decode byte 0x95 in position 7490: invalid start byte"}], 'warnings': [{'message': 'Protocol declared but not used', 'code': 1019, 'supplemental': "protocols declared in the file **s_sacurine.txt** are not used in any assay file: {'annotation-CEA', 'preprocessing'}"}, {'message': 'A required property is missing', 'code': 4003, 'supplemental': 'A property value in Investigation Title of investigation file at column 1 is required'}, {'message': 'A required property is missing', 'code': 4003, 'supplemental': 'A property value in Investigation Description of investigation file at column 1 is required'}, {'message': 'A required property is missing', 'code': 4003, 'supplemental': 'A property value in Study Person Mid Initials of investigation file at column 2 is required'}, {'message': 'Missing Term Source REF in annotation or missing Term Source Name', 'code': 3008, 'supplemental': "Incomplete values for ontology headers, for the field 'Characteristics[organism]' in the file '**s_sacurine.txt'**. Check that all the label/accession/source are provided."}, {'message': 'Missing Protocol declaration', 'code': 1007, 'supplemental': "Protocol(s) of type ['extraction'] defined in the ISA-configuration expected as a between 'Sample Name' and 'Extract Name' but has not been found, in the file **'a_sacurine.txt'"**}, {'message': 'Missing Protocol declaration', 'code': 1007, 'supplemental': "Protocol(s) of type ['labeling'] defined in the ISA-configuration expected as a between 'Extract Name' and 'Labeled Extract Name' but has not been found, in the file **'a_sacurine.txt'**"}]}
 
This currently leads to inconsistent reporting/results.

**Comment by djcomlab** [comment]
Yep, this is a bug because of a bad use of ``global`` vars in the code. This was already fixed in the repo but hasn't yet been pushed to a release distribution.

**Comment by djcomlab** [comment]
Fixed in v0.3.5, closing...
