### ISSUE TITLE
a function to merge 2 isa-tab files

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#165]
UC provided by Ralf Weber:
merge an ISA tab created with mzml2isa with an ISA file created with the API function.
input = 2 ISA-Tab files corresponding to the same experiment.
output = 1 single ISA file 
(indirectly present in the mzml2isa tool though)
This is more a case of annotation upgrade

**Comment by agbeltran** [comment]
To be discussed in more detail with Ralf and get a set of test files.
