### ISSUE TITLE
API Create mode: make it aware of Quality Control element

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#166]
provide the capability to create QC elements based on the PhenoMenal agreed upon terms.
(relates to randomization function discussed with Ralf too)

**Comment by djcomlab** [comment]
I've done a fairly basic implementation of this, should be able to try it in this notebook https://github.com/ISA-tools/isatools-notebooks/blob/master/notebooks/Study%20Designer%20(Sample%20QC%20injection).ipynb

**Comment by agbeltran** [comment]
This issue is restricted to QC elements injected at particular intervals. A QCPlan object will be created with all the required parameters (the MaterialType with its characteristics). Other QC elements (e.g. batch termini) will be considered in other issues.

**Comment by djcomlab** [comment]
Add characteristics (any) to QC injection plan; add interval offset

**Comment by djcomlab** [comment]
This is completed in the API and in the Galaxy tool, closing.
