### ISSUE TITLE
Performance issues with ISA-Tab parser on larger tables

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#168]
ICL report some blocking performance issues with loading larger tables (3000+ assays) when using the ISA-Tab parser.

In tests, it takes around 40 minutes to load into Python ISA-Tab objects using the ISA-Tab parser in https://github.com/ISA-tools/isa-api/blob/master/isatools/io/isatab_parser.py

We need to run some profiling on the parser (see https://docs.python.org/2/library/profile.html).

**Comment by agbeltran** [comment]
A new parser is being developed to deal with this performance.

**Comment by djcomlab** [comment]
New parser in ``isatab.load()``, tests in ``test_isatab.py`` and via ``isatab2json`` with new parser in ``test_isatab2json.py``
