### ISSUE TITLE
isatab2json conversion

### ISSUE THREAD

**Issue by yjarosz** [ISA-tools/isa-api#170]
When following the tutorial and creating my first ISA tabs: [createSimpleISAtab.py](https://github.com/ISA-tools/isa-api/blob/master/isatools/examples/createSimpleISAtab.py),

Works fine as I got my 3 files under some `./data` directory.
I tried the next step in the tutorial as [Converting to JSON](https://isatools.readthedocs.io/en/latest/conversions.html) and I got this error:

```
In [24]: isa_json = isatab2json.convert('./data', validate_first=False)
2016-11-29 11:03:55,676 INFO: Converting ISA-Tab to ISA JSON...
2016-11-29 11:03:55,676 INFO: Converting ISAtab to ISAjson for ./data
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-24-a95320690575> in <module>()
----> 1 isa_json = isatab2json.convert('./data', validate_first=False)

/Users/yohan.jarosz/miniconda3/envs/dp/lib/python3.5/site-packages/isatools/convert/isatab2json.py in convert(work_dir, identifier_type, validate_first)
     40     converter = ISATab2ISAjson_v1(identifier_type)
     41     logger.info("Converting ISA-Tab to ISA JSON...")
---> 42     return converter.convert(work_dir)
     43
     44

/Users/yohan.jarosz/miniconda3/envs/dp/lib/python3.5/site-packages/isatools/convert/isatab2json.py in convert(self, work_dir)
     95
     96
---> 97         isa_tab = parse(work_dir)
     98         #print(isa_tab)
     99

/Users/yohan.jarosz/miniconda3/envs/dp/lib/python3.5/site-packages/isatools/io/isatab_parser.py in parse(isatab_ref)
    114         rec = i_parser.parse(in_handle)
    115     s_parser = StudyAssayParser(isatab_ref)
--> 116     rec = s_parser.parse(rec)
    117     return rec
    118

/Users/yohan.jarosz/miniconda3/envs/dp/lib/python3.5/site-packages/isatools/io/isatab_parser.py in parse(self, rec)
    249         final_studies = []
    250         for study in rec.studies:
--> 251             source_data = self._parse_study(study.metadata["Study File Name"],
    252                                             self._col_types["node"])
    253                                             #["Source Name", "Sample Name", "Comment[ENA_SAMPLE]"])

KeyError: 'Study File Name'
```

Is this something that I should not try? Or is this supposed to works?

**Comment by djcomlab** [comment]
Hi, thanks for the report, just looking into it.

**Comment by djcomlab** [comment]
Hi Yohan, this is definitely a bug, and a weird one so is taking a bit longer to fix than I though. Thanks for reporting it, as the example code is brand new and seeing how it works with other parts of the API is something we had not yet done.

To get it moving you can try providing identifiers to both the investigation and study objects, e.g.

```
investigation.identifier = "i1"
study.identifier = "s1"
```

however then another bug comes up in post-validating the ISA JSON produced from the ``isatab2json`` conversion (which happens automatically):

```
jsonschema.exceptions.ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['studies']['items']['properties']['assays']['items']['properties']['processSequence']['items']['properties']['executesProtocol']['properties']['@id']:
    {'format': 'uri', 'type': 'string'}

On instance['studies'][0]['assays'][0]['processSequence'][1]['executesProtocol']['@id']:
    None
```

Will keep you posted by updating this issue as I progress.

**Comment by yjarosz** [comment]
Hi,
so yes, I can confirm that it is working after settings the identifiers.
Maybe it could be generated automatically on `__init__`?

Then I got the same error with `validate_first=False`. Set it to `true` and I got 
```
2016-11-30 10:49:36,372 INFO: Validating input ISA tab before conversion
2016-11-30 10:49:36,456 ERROR: (E) Could not load configuration for measurement type '' and technology type '' for STUDY ASSAY.0'
2016-11-30 10:49:36,462 CRITICAL: Could not proceed with conversion as there are some fatal validation errors. Check log.
```

So it might be ok to fail here if the ISA tab is also not valid?

**Comment by djcomlab** [comment]
Hiya, so in this case if the ISA-Tab is not completely valid we prevent the conversion when ``validate_first=True``. Strictly speaking a ``measurement_type`` and ``technology_type`` should be set for an assay, so in the example you could add something like:

```
assay.measurement_type = OntologyAnnotation(term="gene sequencing")
assay.technology_type = OntologyAnnotation(term="nucleotide sequencing")
```

before generating the ISA-Tab.

Also if the investigation and study identifier fields are not set, the code should still work, so am working on that. The generated ISA-Tab looks fine on the face of it, but when it is put into ``isatab2json`` converter, and also into the ``isatab.validate2()`` validator, it fails and I am investigating this.

**Comment by djcomlab** [comment]
Re: ``jsonschema.exceptions.ValidationError: None is not of type 'string'`` problem, narrowed it down to the generated ISA-Tab assay file missing ``Raw Data File`` column heading above the ``sequenced-data-*`` values.

**Comment by djcomlab** [comment]
When creating ``DataFile`` objects, need to remember to add ``label`` that stores the data file header in ISA-Tab, e.g.

```
datafile = DataFile(filename="sequenced-data-{}".format(i), label="Raw Data File")
```

Will update documentation accordingly.

**Comment by yjarosz** [comment]
Hey,

thank you, that's working perfectly 👍

**Comment by djcomlab** [comment]
Thanks for trying it out!

In fact this example code isn't yet pushed out in our release, so you're a very early adopter!
