### ISSUE TITLE
MW2ISA failing tests in Jenkins (Phenomenal)

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#177]
mw2isa function needs refactoring for better integration in ISA-api.
failure revealed during PhenoMenal Testing Hackathon.
allow mw2isa api call to:
-use a MW access number as sole input
-allow optional download of raw archives from MW
-allow optional invoking of ISA python validator
-improve overall error catching

**Comment by proccaserra** [comment]
requires new release of API (but test integration before release, not like last time) so the docker container can be also checked

**Comment by djcomlab** [comment]
Fixed, closing.
