### ISSUE TITLE
JSON files in ISA archive 

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#18]
Will ISA with JSON serialisation be using the same approach of separate  i_* , s_* and a_* files as ISA-TAB, or one JSON file for everything is envisaged? 

Sorry if this is already addressed in the documents, could not find a reference.

**Comment by djcomlab** [comment]
Currently the idea is to support having individual JSONs inside an ISArchive (so a zip with i_*/s_*/a_* files) similar to the ISA-Tab, and also support a single JSON that combines all three parts where appropriate.

**Comment by vedina** [comment]
Thanks!

**Comment by agbeltran** [comment]
Nina, if you have any other requirements let us know. Thanks!

**Comment by vedina** [comment]
@agbeltran sure, more questions coming!

**Comment by djcomlab** [comment]
This ticket is closed since October 2015, so not sure why I've been assigned here.

**Comment by agbeltran** [comment]
Because you took care of it at the time :)
