### ISSUE TITLE
Export ISArchive zip files from ISA content

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#180]
A feature to export ISA content as an ISArchive zip containing ISA-Tab and raw files referenced in by the ISA-Tab table files.

See https://github.com/ISA-tools/ISAcreator/blob/development/src/main/java/org/isatools/isacreator/archiveoutput/ArchiveOutputUtil.java for this feature implemented in ISA creator.

**Comment by agbeltran** [comment]
When considering the archival functionality, we need to include the option to only archive a subset of assays as requested in https://github.com/ISA-tools/ISAcreator/issues/291
