### ISSUE TITLE
Access to individual ISA-Tab files independently (for simple tweaks only)

### ISSUE THREAD

**Issue by jrmacias** [ISA-tools/isa-api#185]
This is mainly a feature request. Regarding a simple method to access (read/write) individual files for simple modifications. Sample case: if I only need to change the study title... would I need to parse the whole (and deal with the complexity of validations and so on) or just load the i_investigation.txt into its Python v1 model, make the (simple) change and dump it back ?

**Comment by djcomlab** [comment]
Hi Jose, at the moment it requires loading the whole set of ISA files. But yes it does make sense to be able to programmatically make edits to just the ``i_*.txt`` file (and each of the other files) to do simple edit.

We can certainly implement this as a new feature.

**Comment by jrmacias** [comment]
Hi David, thanks for considering.

**Comment by agbeltran** [comment]
+1, this could be really useful to avoid loading the whole ISA-Tab, but we should consider changes that may affect the validity of the files; e.g. if the change in the study file is about adding an annotation, it may require to include a new ontology in the ontology references in the investigation file

**Comment by djcomlab** [comment]
Implemented loading of i_.txt file and skipping loading study and assay table files for small tweaks with `skip_load_tables=True` on `isatab.load()` and `skip_dump_tables=True` on `isatab.dump()`, and added example code on this in https://github.com/ISA-tools/isa-api/blob/develop/isatools/examples/modifyInvestigationOnly.py

R/w of table files independently doesn't really make sense since there is information in these files needed to be synchronised up to the i_.txt file.

**Comment by jrmacias** [comment]
Hi ISA Team,
Thanks a lot for taking the time to implement this feature. It is being very useful for the purpose we had in mind.
Just wondering... this is not available yet through pip, is it?

**Comment by djcomlab** [comment]
Hiya, no not in pip yet as we're currently finishing up something else that will go into the next release. Please feel free however to pull from master and try it out. 

Just remember to use `skip_load_tables=True` on `isatab.load()` and `skip_dump_tables=True` on `isatab.dump()`

**Comment by jrmacias** [comment]
Right, that is what I'm doing... (locally in my development environment) So far it works nicely. Thanks a lot.
