### ISSUE TITLE
ValueError: ('Could not resolve Protocol parameter from Parameter Value ', 'Post Extraction')

### ISSUE THREAD

**Issue by jrmacias** [ISA-tools/isa-api#189]
ValueError: ('Could not resolve Protocol parameter from Parameter Value ', 'Post Extraction') is raised when using the new parser in isatab2json.convert(path, validate_first=False, use_new_parser=True) with some MTBLS studies (i.e. MTBLS73) not with others (i.e. MTBLS83).

...
ISA = isatab.load(open(i_files[0]))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/isatools/isatab.py", line 3005, in load
    study.factors).create_from_df(assay_tfile_df)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/isatools/isatab.py", line 3566, in create_from_df
    raise ValueError("Could not resolve Protocol parameter from Parameter Value ", category_key)
ValueError: ('Could not resolve Protocol parameter from Parameter Value ', 'Post Extraction')

**Comment by proccaserra** [comment]
@jrmacias i can not access the ISA archive to check it. Can you confirm that the Parameter "Post Extraction" is declared in the Protocol section of the i_inv file? (and matches case, with not trailing white space?)

If Parameter properly declared, could you send us the files  so we can carry out tests?
thx

**Comment by jrmacias** [comment]
That parameter is not present in i_*.txt for MTBLS73, but appears in MRBLS83.
Could it be a wrong formatted study?

**Comment by djcomlab** [comment]
So some MTBLS studies don't covert because of problems in the ISA-Tab.

In this case the Parameter Value JSON fragment cannot be created as it relies on linking to a declared Parameter. Parameters are created from the content in the investigation file study protocol parameters declaration. If the protocol parameter does not exist in the investigation file description (or names do not match exactly), this will raise the error you're experiencing.

**Comment by proccaserra** [comment]
ok, the Parameter Name is not declared in this submission so when invoking the key via the API, the parser can’t find it and throws an exception.

note: MTBLS73 has 2 investigation files, and several more parameters present in the assay tables are not declared in the investigation files.
Any MTBLS with similar non declared protocol parameters will fail against the new API.
Fix: add Protocol Parameters to the relevant protocols in the i_inv.txt file

I will then be closing the issue as the software behaves as expected
