### ISSUE TITLE
BioSamples/SampleTab import to ISA

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#190]
Related to #120

**Comment by proccaserra** [comment]
ftp://ftp.ebi.ac.uk/pub/databases/biosamples/sampletab/GSB-718.txt

from ISA study sample table: 
s/Protocol REF/Characteristics[protocol.type]/
Group Name may be generated from a vector of Factor Value[] (if available)

s/Term Source Accession/Term Source ID/
