### ISSUE TITLE
Enable Support of  2 'Sample Name' chaining to allow representation/tracking of Aliquots

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#191]
Required by Imperial (and most likely all phenome centres): requested by Jake Pearce/Nourredin Sadawi

Protocol type should be set to 'aliquoting' to allow standard parsing.

ISAcreator-1.7+ currently support multiple Sample Name occuring on the Assay Table
        <field header="Sample Name" data-type="String" is-file-field="false"
            **is-multiple-value="true"** is-required="true" is-hidden="false" is-forced-ontology="false">
            <description><![CDATA[Samples represent major outputs resulting from a protocol application other than the special case outputs of Extract or a Labeled Extract.]]></description>
            <default-value><![CDATA[]]></default-value>
            <generated-value-template>[INSTITUTION].Group-[GROUP_NO].Subject-[SUBJECT_NO].[SAMPLE_EXTRACT]</generated-value-template>
        </field>

In case, ISA users were to prefer coding aliquoting event at the 'studySample' level, it would require
modifying ISA configuration to set the 'is_multiple_value' to 'true' in the studySample.xml file:

<field header="Sample Name" data-type="String" is-file-field="false"
            is-multiple-value="true" is-required="true" is-hidden="false"
            is-forced-ontology="false">
            <description><![CDATA[Samples represent major outputs resulting from a protocol application other than the special case outputs of Extract or a Labeled Extract.]]></description>
            <default-value><![CDATA[]]></default-value>
        </field>

**and** amend the ISA java parser/validator, which seems confused if multiple 'Sample Name' header appear in that Table.

TODO: Check if and how ISA-API and ISA python validator/converter handle these representations

TODO: produce ISA-TAB files for testing

**Comment by djcomlab** [comment]
Fixed in develop, closing
