### ISSUE TITLE
Trouble using isatab.dump

### ISSUE THREAD

**Issue by yjarosz** [ISA-tools/isa-api#200]
Hi,

I got a traceback that I didn't succeed to resolve using `isatab.dump` method.

Basically I have isa-tab files that I load with the API, then I dump them in another directory and I got the following traceback:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    investigation = dump(investigation, 'output')
  File "/Users/yohan.jarosz/Programmation/isa-api/isatools/isatab.py", line 404, in dump
    write_assay_table_files(investigation, output_path)
  File "/Users/yohan.jarosz/Programmation/isa-api/isatools/isatab.py", line 637, in write_assay_table_files
    for node in _longest_path_and_attrs(paths):
TypeError: 'NoneType' object is not iterable
```

I created a zip archive with the code / configuration files & isa-tab files I use:
[test02.zip](https://github.com/ISA-tools/isa-api/files/818752/test02.zip)

Could you give some advice?

**Comment by djcomlab** [comment]
Hi @yjarosz, can you please confirm which version of ISA API you are using? Is it installed from PyPI, and if so, which version number? Otherwise please confirm if you are trying it out from source and which branch.

**Comment by djcomlab** [comment]
Testing against latest source, I can confirm this is a bug with loading the ISA-Tab example here. Will investigate further.

**Comment by yjarosz** [comment]
Hi, I'm from `master` 0eb06bf.
Will try with newer if you need.

**Comment by djcomlab** [comment]
Thanks, this is definitely a bug, am working on fixing it. Will let you know when a fix is ready! Sorry for the inconvenience.

**Comment by yjarosz** [comment]
No problem ;) Thanks for the support.

**Comment by djcomlab** [comment]
Hi @yjarosz I've pushed some fixes to the `develop` branch, please try it out (I've also implemented your scenario in a test). Note that when you `dump` out to ISA-Tab, at the moment it drops columns that are entirely empty so the output might differ a little from the input in this case.

**Comment by yjarosz** [comment]
Hello @djcomlab . I was away for some time.
It works for this test now it's okay.

But i have still trouble to apply to my use case: I will try to explain here, but maybe mail / other issue could be better, you tell me ;)

Basically, I try to construct ISA objects, respectively (Investigation, Study and Assay) without any isatab files. 

* I build `I` and `S` objects programatically (adding description, contatcs, ...)
* Then  I try to build the Study process sequence using `isatab.ProcessSequenceFactory`:
    * Load protocols from a `StudySample.xml` using `isatab_configurator`.
    * Loop over the fields to get the protocols parameters and add them to the protocol.
    * Load an excel file that correspond to a study file into a dataframe
    * Use `ProcessSequenceFactory` to properly get `Sources`, `Samples`, and so on...
* Then I do the same for an assay file.
* Then I `dump` the objects to get a properly generated investigation file.

The reason I'm doing this is that I would like to give my colleagues an excel file they can more or less load and validate through a web interface without them using isacreator application. I would also like 
to maybe get rid of the excel files for some colleagues that would like to create those entry via an automatic process/API.
It was more or less working (but the bug I presented) but I see it has been refactored since and I'm not sure I'm on the right track now :)


For now I can work around this building process by just dumping the `I` object to an investigation file alone, then reloading with `isatab.load` with the excel files converted to TSV. I just find it a bit cumbersome and I would like to avoid the process of writing to the disk if possible.


Do you think it could make sense? Would it be possible to give a dataframe to isatab library so we can generate the isatab files?

**Comment by djcomlab** [comment]
Hi Yohan, thanks for describing what you're trying to do. I'll close this bug issue and move the more detailed conversation about that to our ISA team support list.
