### ISSUE TITLE
sampleTab conversion hangs on ICL-ISATAB-sample

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#209]
was attempting to generate a sampleTab from isatools-0.7.5 using the file sent my Noureddin at ICL last week.
no error thrown, just hangs

**Comment by djcomlab** [comment]
Doesn't hang for me - what command exactly are you running?

**Comment by proccaserra** [comment]
from http://isatools.readthedocs.io/en/latest/exportdata.html but directly passing argument works, closing,

**Comment by djcomlab** [comment]
The documented way should work as it's the same way as how the test runs... I'll still take a look.
