### ISSUE TITLE
ISA v1 JSON examples

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#21]
In addition to the schema I am looking for ISA-JSON examples (both v1 and v2). 

We've tried locally https://github.com/ISA-tools/isa-rest-api and it converts (some of our) ISA-TAB archives to JSON v1 (some fail). Wondering how complete is the convertor at this moment. For example I can't find the input/output chain in JSON neither in our tests , nor in this [BII-I-1 JSON](https://raw.githubusercontent.com/ISA-tools/isa-rest-api/master/tests/data/BII-I-1.json) . 

The reason to look for examples is it is not clear for me from the schema how the chains will be represented. The input/output nodes of the [process chain](https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/process_schema.json) refer to the same schema ([material](https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/material_schema.json), [data](https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/data_schema.json)) as for describing sources and samples.  Are these going to be repeated in the input/output chain, or referred by some identifier?  

I could guess the JSON v1 schema follows very closely the Java object model as used [before](https://github.com/ISA-tools/ISAvalidator-ISAconverter-BIImanager), but in the Java model the references are just pointing to the same objects, while not sure how this will look in JSON.

**Comment by agbeltran** [comment]
Hi @vedina, we are completing the conversion (the one you accessed through the service is not the latest version) and will provide examples soon. The model we are relying on is more like the [linkedISA model](https://github.com/ISA-tools/linkedISA/tree/master/isa-graphparser/src/main/java/org/isatools/graph/model) rather than the one in the import_layer.

**Comment by vedina** [comment]
Thanks for the hint!   Which script / tool do you suggest to use for conversion?

**Comment by vedina** [comment]
@agbeltran could you please check if there is a problem with the ISA terms link http://purl.org/isaterms 

it is reference [35](http://www.biomedcentral.com/1471-2105/15/S14/S4#B35) in the [linked ISA](http://www.biomedcentral.com/1471-2105/15/S14/S4) paper

**Comment by agbeltran** [comment]
Thank you @vedina for reporting this - it is due to a VM being down. While I fix this, you can access the ontology here: https://github.com/ISA-tools/linkedISA-ontologies

**Comment by agbeltran** [comment]
Some example json data have been added here: https://github.com/ISA-tools/isa-api/tree/develop/isatools/sampledata

**Comment by vedina** [comment]
Thanks!
