### ISSUE TITLE
Add utility function for addition of a protocol to a study, preventing duplicates

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#211]
Currently, using the model, users of the API need to control the creation of duplicates when adding protocols to a study object. Add a utility function that makes this check when adding a protocol.

The uniqueness of protocols is established by its name, and if an ontology annotation exists, by checking both name and ontology annotation.

**Comment by djcomlab** [comment]
Implemented in `isatools.model.Study.add_prot()`, closing

https://github.com/ISA-tools/isa-api/blob/f564d195811a1e4375da94f6d53707f90564eaf3/isatools/model.py#L1656-L1670

Closing
