### ISSUE TITLE
investigation without biological material (ISA v1)

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#22]
What would be the correct way to represent an experiment not involving biological material - i.e. what should be the `Source` node for physico-chemical measurements of a sample.

**Comment by proccaserra** [comment]
@vedina , create a 'source Name', set its value, then associate a 'Material Type', and set it to 'non biological entity' or something similar to indicate a man made chemical entity. 
All assays made on such entities could/should be grouped in 'physico-chemical' study. A second study to assess the biological effects on these np would have to coded in a second study. Ideally, the np should be uniquely identified so it can be made obvious that the intervention in the second study uses the material tested for Phy-Chem properties in the first study.
