### ISSUE TITLE
needed minor fixes in isa_model_version_1_0_schemas

### ISSUE THREAD

**Issue by ntk73** [ISA-tools/isa-api#23]
In order to generate automatically Java classes from the schemas for isa v.1.0 we used jsonschema2pojo CLI application. The generation failed (several exceptions were thrown). The three problems appear to be due to following small typos/errors:

(1) in material_schema.json

"items" :  {
                "$ref": "material_attribute_schema.json#characteristic"
                }
changed to:
"items" :  {
                "$ref": "material_attribute_schema.json"
                }

(2) in process_schema.json

"executesProtocol": {
                "$ref": "protocol.json#"
        },
changed to:
"executesProtocol": {
                "$ref": "protocol_schema.json#"
        },

(3) in sample_schema.json

"items" : {
               "$ref" : "factor_value.json#"
            }

changed to:

"items" : {
               "$ref" : "factor_value_schema.json#"
            }

The problems (2) and (3) are caused by missing   "_schema" in the "$ref" definitions

I am not sure for the first case (1).

**Comment by agbeltran** [comment]
@ntk73 Thanks for reporting those errors - they are now fixed.

**Comment by agbeltran** [comment]
@ntk73 - could you point me to the repo where you are generating the Java classes with jsonschema2pojo? Thanks
