### ISSUE TITLE
create test examples for various designs

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#231]
to be used for code testing

**Comment by agbeltran** [comment]
This refers to creating input examples to test the create mode for different designs. Provide parameters for SampleAssayPlan object and expected outputs (e.g. in terms of group size).

**Comment by agbeltran** [comment]
The example summarization of designs are at: https://github.com/ISA-tools/isa-api/blob/feat/create/isatools/create/test-examples.txt
