### ISSUE TITLE
create a curation function to recast spurious Factor Value into either Parameter Values or Characterisitics

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#237]
Batch processing of ISA-Tab files from public repositories reveals declaration of spurious Factor Values.
Code has been developed to detect those cases. We need code to assist the correction of these files.
Given a list of 'Factor Value' names, the function should recast those fields as Characteristics and attached them to the Source Name unless specified otherwise by the curator.
The curator may deem necessary to cast such 'Factor Values' as Protocol Parameter Values. The function may allow to do so but would require interaction with the user to identify the relevant Protocols and their type.

**Comment by djcomlab** [comment]
Also make an example script to be able to run the fixes as a batch.

**Comment by proccaserra** [comment]
doing some testing and noticed that ISATabFixer worked nicely as expected but it forgets to remove the factors from the StudyFactors list in the investigation file.

**Comment by djcomlab** [comment]
Fixed in https://github.com/ISA-tools/isa-api/commit/05d1a4f0133199c2cab8d0463ba34fcf9304b766, closing again...
