### ISSUE TITLE
Representation of experimental data extracted from literature

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#24]
Representing experimental data extracted from published literature is a very common use case, but not straightforward to fit into ISA model.

The samples, the protocols, the assays will be different across papers.   As the goal of data gathering exercise is to be able to combine the data from different papers, one investigation per paper is not necessary the right approach. If combining into single investigation, then I am not aware of means to assign the publications to particular assays or samples. 

What would be the recommended approach?

**Comment by proccaserra** [comment]
@vedina Could you elaborate on the use case as it may also depend on the quite of data being collected from a particular publication and whether you have access to the raw data or not. To best answer your question and determine which ISA object needs to be used, we need to get from you the type of information you would typically extract from a series of related manuscripts. We could start a google doc for that purpose.

**Comment by vedina** [comment]
The typical use case is there is no access to the raw data.  The type of the data and the level of details extracted may differ greatly. There are many many projects whose main activity is gathering the data from the literature, and the common scenario is using custom spreadsheets.

**Comment by proccaserra** [comment]
Hi Nina, getting back on your question. You stated that access to raw data would be excluded in such case. This points to a different use case that the one defining ISA. It sounds more like a request for specifying facts, findings alongside evidence confidence indicator. Can you post an example of data collected in such way that you have been dealing with? I would particularly insist on the clearly identifying the dimensions being measured.

**Comment by vedina** [comment]
Hi Philippe,

* A very typical case is this dataset [Benchmark Data Set for In Silico Prediction of Ames Mutagenicity](http://doc.ml.tu-berlin.de/toxbenchmark) , publication [doi:10.1021/ci900161g] (http://pubs.acs.org/doi/abs/10.1021/ci900161g) (widely used for modelling). It contains a single column on activity: `Activity: 0 indicates negative compounds, 1 indicates positive compounds`.  

* More recent exercise in the nanomaterials domain, and trying to use ISA-Tab-Nano , also for data gathered form the literature [doi:10.3762/bjnano.6.202](http://www.beilstein-journals.org/bjnano/single/articleFullText.htm?publicId=2190-4286-6-202)
