### ISSUE TITLE
derives relation between material?

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#26]
instead of relying on Protocol  Applications:
suggestion from COPO project:
COPO folks were asking about a way to link sources and samples (both ways I suppose, but maybe mainly from samples back to sources).

The current model allows this only through a process (which can be implicit in the ISA-tab files).

Do we want to allow more direct links? I think this would make the model less consistent but we can consider that...

**Comment by djcomlab** [comment]
So one question is whether making the changes to how we represent links between sources and samples makes the ISA-JSON less consistent with the ISA-Tab and ultimately the ISA v1 specification. 

My feeling is that if a Process is required, even if implicit and not described, we should not shortcut to keep the JSON serialization consistent with the v1 spec and model. If we want to update how we represent something, we should make an update to the spec, and then update the serializations.

**Comment by djcomlab** [comment]
@agbeltran should join in this thread!

**Comment by proccaserra** [comment]
@djcomlab so we maintain Process as required but we could enhance the serialization after validation with 'shortcuts'. If the COPO use case relates to the ability to provide faster ways to get all related samples, we could consider it. The documentation would have to be clear that producing an ISA-JSON only with 'shortcut' would fail validation. Would that cover it all?

**Comment by djcomlab** [comment]
We could make the validation relax to allow the shortcut? Would that work?

**Comment by agbeltran** [comment]
If we add the relationship in the schemas, we would have the serialization and validation in one go. We need to harmonize v1 and v2 anyway, as v2 has a 'material object' while v1 simplifies this into 'source' and 'sample' without requiring definition of roles.

**Comment by agbeltran** [comment]
This issue was raised by @shaw2thefloor and @tonietuk. Toni and Felix, feel free to comment on your use case if you see fit. Thanks!
