### ISSUE TITLE
isatab.validate() doesn't support data type 'double'

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/isa-api#260]
WARNING:isatools.isatab:(W) Unknown data type 'double' for field 'x' in the file 'x'
in validating data against a phenotyping-field configuration containing 'Double' parameters.

**Comment by djcomlab** [comment]
The problem here is that the validator is trying to match from the configuration the keyword `Float` for decimal numbers instead of `Double`.

**Comment by djcomlab** [comment]
Fixed in https://github.com/ISA-tools/isa-api/commit/b1932a9090737df838a5e67c934ee963e0db1c20, closing
