### ISSUE TITLE
isatab.check_ontology_field.check_single_field should be negated

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/isa-api#261]
the functions checks if all the fields have values, and if so it warns that something is missing

**Comment by agbeltran** [comment]
Adding link to line in the code: https://github.com/ISA-tools/isa-api/blob/49c36f8d180057832a1ab0711dacff07e3d04926/isatools/isatab.py#L2433

**Comment by djcomlab** [comment]
The function is supposed to check if the ontology annotation fields are correctly supplied (rule #3010 from https://docs.google.com/spreadsheets/d/1avWQy1eW0FApjOT5-UHOUUopi1-Mt1ehe4LntrKz5ok), i.e.:

Term is present and no Term Source REF and Term Accession == OK
Term and Term Source REF present and no Term Accession == OK
Term and Term Accession but no Term Source REF == not OK
No Term == not OK

**Comment by djcomlab** [comment]
Logic fixed in https://github.com/ISA-tools/isa-api/commit/9ff077dbc0f3d8d57cb214ae567fb0b4a3aeeb1a, closing...
