### ISSUE TITLE
isatab.check_ontology_fields complete implementation to check against declared ontology sources

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#262]
Related to #261 and left as a TODO in https://github.com/ISA-tools/isa-api/blob/49c36f8d180057832a1ab0711dacff07e3d04926/isatools/isatab.py#L2445

**Comment by djcomlab** [comment]
Implemented in 2ca5c64c6b84cc0ecab56c420a54d1358ac040f1
