### ISSUE TITLE
isatab.check_protocol_usage() Remove artificial blank protocol that leads to a warning

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/isa-api#263]
WARNING:isatools.isatab:(W) Some protocols declared in the file 'x' are not used in any assay file: ['']
produced by isatab.check_protocol_usage due to:
        protocols_declared.add('')
        ...
        diff = protocols_declared - protocol_refs_used
        if len(diff) > 0:
            warnings.append({

https://github.com/ISA-tools/isa-api/blob/49c36f8d180057832a1ab0711dacff07e3d04926/isatools/isatab.py#L1385

**Comment by djcomlab** [comment]
The artificial blank needs to be removed from https://github.com/ISA-tools/isa-api/blob/49c36f8d180057832a1ab0711dacff07e3d04926/isatools/isatab.py#L1448 with `- {''}` like in https://github.com/ISA-tools/isa-api/blob/49c36f8d180057832a1ab0711dacff07e3d04926/isatools/isatab.py#L1658
