### ISSUE TITLE
Factors declared in the middle of Study ignored

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/isa-api#270]
In isatab2json conversion the factors declared in the middle of the tab file get ignored. Moving them to the end of the tab file (after Sample Name) makes them appear in json representation.
The spec doesn't require them to be at the end, does it?

**Comment by djcomlab** [comment]
As discussed, the spec does not require the FVs to be at end of table, but is recommended only in the implementation guidelines.

The parser should be fixed to support picking up the FVs in other positions.

**Comment by djcomlab** [comment]
Fixed in 0accbe4f5e78c5dd456e73bb6b2e1164d4e828c9
