### ISSUE TITLE
Add string trimming in parsing/validation of tab files

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/isa-api#271]
String trimming could improve user experience with tab format. It seems that currently the strings are taken as they are written, so that
`Parameter Value[param1]` != `Parameter Value[param1 ]`
and doesn't match the name declared in Investigation within a multivalued string (split only at semicolon) as:
`Study Protocol Parameters Name	param0; param1`
Allowing for white space inconsistencies could facilitate file preparation and validation. Especially in the last case the spaces seem natural and reasonable due to better readability.

**Comment by djcomlab** [comment]
Completed in develop, closing...
