### ISSUE TITLE
Extend the documentation about validation referring to the rules

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#273]
It would be useful to extend the documentation about validation available here:
https://isatools.readthedocs.io/en/latest/validation.html
referring to the validation rules:
https://docs.google.com/spreadsheets/d/1avWQy1eW0FApjOT5-UHOUUopi1-Mt1ehe4LntrKz5ok/edit#gid=0

**Comment by proccaserra** [comment]
available from current documentation
