### ISSUE TITLE
Handling of empty OA's for multiple valued fields

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/isa-api#282]
There's an unhandled Index-out-of-range exception for multiple valued fields with empty Ontology Annotation field: 
https://github.com/ISA-tools/isa-api/blob/e56c644a305e91509281540674bc910d0080d170/isatools/isatab.py#L2763
unless there are semicolons separating the empty OAs:
```
Study Protocol Parameters Name	param1;param2
Study Protocol Parameters Name Term Accession Number	;
Study Protocol Parameters Name Term Source REF	;
```
which isn't a natural thing to do when describing the data manually.
It could be handled by assuming that an empty string means empty OAs for all values.

**Comment by djcomlab** [comment]
Completed in develop, closing...
