### ISSUE TITLE
Extend implementation of isatools.create.models.IsaModelObjectFactory 

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#284]
The isatools.create.models.IsaModelObjectFactory class supports creating ISA content from a pair of (treatment_sequence, sample_assay_plan) objects. 
The InterventionStudyDesign class is composed of an ordered dictionary of pairs of (treatment_sequence, sample_assay_plan).
We should extend the implementation of the IsaModelObjectFactory to create ISA content from an InterventionStudyDesign object (basically, support to build ISA objects from pairs of treatment sequences and sample assay plans, and not just one pair).

**Comment by djcomlab** [comment]
This has been implemented with a generic `StudyDesign` class in https://github.com/ISA-tools/isa-api/blob/a227d2af13c4e357aeea6f65e05a7229429e9d94/isatools/create/models.py#L1214 that couples `Treatment`s with `SampleAssayPlan`s inside each `StudyEpoch` object.
