### ISSUE TITLE
MTBLS.get('...') Does not work when setting target_dir

### ISSUE THREAD

**Issue by nsadawi** [ISA-tools/isa-api#289]
without target_dir it downloads to a `tmp` folder, when setting `target_dir` to an existing empty dir it does nothing

**Comment by djcomlab** [comment]
@nsadawi Which study are you trying to get?

**Comment by djcomlab** [comment]
@nsadawi And are you using a full path or relative path?

**Comment by nsadawi** [comment]
@djcomlab  my apologies .. it actually works .. no idea what I did incorrectly
Many thanks
