### ISSUE TITLE
Add identifier attribute to TreatmentSequence

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#298]
As required in #297, an identifier attribute is needed for the TreatmentSequence class

https://github.com/ISA-tools/isa-api/blob/a7a1b8e4290ce608ed146a9a227c7fe787bb0490/isatools/create/models.py#L185

**Comment by djcomlab** [comment]
`TreatmentSequence` is now represented as a `StudyArm` list of `StudyEpoch`, with identifiers using `.name` attributes. https://github.com/ISA-tools/isa-api/blob/02d349412b39f5844ebc3c55e82d9d7b181a4361/isatools/create/models.py#L1178
