### ISSUE TITLE
Adding Comment field using API does not work

### ISSUE THREAD

**Issue by nsadawi** [ISA-tools/isa-api#299]
Hi, I tried:
`source = Source(name='source_material)`
`source.add_comment(name='Study Name', value_='Flower')`

But it does not work .. it saves with no errors but the Comment field is not there

probably the bug is here:
https://github.com/ISA-tools/isa-api/blob/master/isatools/isatab.py#L682-L685

Many thanks

**Comment by djcomlab** [comment]
Thanks @nsadawi; this is due to some incomplete implementation in the ISA-Tab writer. Will fix this ASAP.
