### ISSUE TITLE
Schema support for numeric factor values?

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#30]
I am wondering where one could specify numeric factor values.

The schema seems to have support for units, and factors specified by ontology entries,  but not for numbers. Could you please clarify?

https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/core/factor_value_schema.json

**Comment by agbeltran** [comment]
Hi @vedina 
The name we had chosen for the property might not have been the best one.
See the current version of the schema here:

https://github.com/ISA-tools/isa-api/blob/feat/conversion/isatools/schemas/isa_model_version_1_0_schemas/core/factor_value_schema.json

(we will merge into develop and then master branches too)

The value can actually be a numeric value (and it won't have an Term Source REF and Term Accession Number in that case, but will only be using the "name" property of the ontologyAnnotation). 

We can actually change "name" to "value" in ontologyAnnotation to make it clearer.

The schemas aim to reflect exactly what the ISA spec v1.0 contains.

**Comment by vedina** [comment]
@agbeltran , could you please clarify.

In the [BII-I-1 example](https://github.com/ISA-tools/isa-api/issues/30) the "rate" should have a numeric value, but I can't find it in the example. 

````
  "factorValues": [
                                {
                                    "value": {
                                        "name": "rate",
                                        "termAccession": "",
                                        "termSource": ""
                                    }
                                },
                              
````

Do you mean it could be written as 

````
  "factorValues": [
                                {
                                    "value": 3.14
                                },
                              
````

and if yes, then how should the schema describe this option?

**Comment by vedina** [comment]
The same issue is valid for characteristics, we'll have to be able to enter numeric values  there as well.

**Comment by vedina** [comment]
@agbeltran could you also add (update) the examples with values using units (and corresponding UO entries).

**Comment by agbeltran** [comment]
@vedina I pushed a complete example for factor values, including units too, see:
https://github.com/ISA-tools/isa-api/blob/develop/isatools/sampledata/BII-I-1.json

we could distinguish numeric values, but as everything in ISAtab is considered a string, I have followed that route. For example:

 "factorValues": [
                                {
                                    "value": {
                                        "name": "ethanol",
                                        "termAccession": "",
                                        "termSource": ""
                                    }
                                },
                                {
                                    "unit": {
                                        "name": "l/hour",
                                        "termAccession": "",
                                        "termSource": ""
                                    },
                                    "value": "0.1"
                                }
                            ],
                            "name": "sample-E-0.1-aliquot6"

Let me know if that closes this issue.

**Comment by vedina** [comment]
Thanks . Would it be possible to write numbers as such in JSON (as it has quite nice support for numbers). It will simplify processing and also
 handling localisation issues (decimal points/decimal commas, thousands separators, etc.) TAB-JSON convertors can serialise these as string in the TAB format.

**Comment by agbeltran** [comment]
@vedina this is now implemented (see develop branch).

**Comment by vedina** [comment]
@agbeltran is this implemented also for parameter values?

**Comment by agbeltran** [comment]
As per in the other issues, yes, it is implemented for process parameter values:
https://github.com/ISA-tools/isa-api/blob/develop/isatools/schemas/isa_model_version_1_0_schemas/core/process_parameter_value_schema.json
factor values:
https://github.com/ISA-tools/isa-api/blob/develop/isatools/schemas/isa_model_version_1_0_schemas/core/factor_value_schema.json
and material attributes (characteristics) values:
https://github.com/ISA-tools/isa-api/blob/develop/isatools/schemas/isa_model_version_1_0_schemas/core/material_attribute_value_schema.json
