### ISSUE TITLE
Fix file pattern identification in SRA conversion 

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#302]
Reported by @tonietuk (COPO project). 

In the SRA conversion code, we are only identifying files with pattern 'xxx.fastq.gz' but if the file pattern is of the type 'xxx.yyy.fastq.gz' (or other combination including dots in the file name), we are not identifying 'xxx.yyy'.

The issue is in the sra.py file at line 197 (see https://github.com/ISA-tools/isa-api/blob/b49e036c1aaa75c9fb6b4634d516e0fdcf58730a/isatools/sra.py#L197).

Example filename: ```BFL_QOSW_3_1_C5LHEACXX.IND1_noribo_clean.fastq.gz```

Errors:
```Failed to validate run xml, error: string value 'IND7_clean' is not a valid enumeration value for type of filetype attribute in type of FILE element in type of FILES element in type of DATA_BLOCK element in RunType```

```Failed to validate run xml, error: string value 'IND1_noribo_clean' is not a valid enumeration value for type of filetype attribute in type of FILE element in type of FILES element in type of DATA_BLOCK element in RunType```

**Comment by tonietuk** [comment]
Hi guys, any update on this issue?

**Comment by djcomlab** [comment]
Hi @tonietuk! Sorry, I've been on leave. Will look into this ASAP myself.

**Comment by djcomlab** [comment]
Fixed in `develop` branch, closing...
