### ISSUE TITLE
Duplicate columns when adding new process

### ISSUE THREAD

**Issue by jrmacias** [ISA-tools/isa-api#303]
Hi,
I am trying to write new processes, in order to add new samples to a study, and experiencing a "funny" behavior: new columns are added at the end of the sample ISA-TAB sample file, duplicating those corresponding to the Factors in the existing samples.
I'll attach a before/after example.
It looks to me that ontology references are not resolved wright, so new Factors are created, appending like an index column to them.

Any idea what is going on here?

[s_MTBLS10-before.txt](https://github.com/ISA-tools/isa-api/files/1871942/s_MTBLS10-before.txt)
[s_MTBLS10-after.txt](https://github.com/ISA-tools/isa-api/files/1871944/s_MTBLS10-after.txt)

**Comment by jrmacias** [comment]
Hi,

This is one of my last tries
       ...
       pre_sample = isa_study.samples[0]
        sample = Sample(name='New-Sample',
                        factor_values=pre_sample.factor_values,
                        characteristics=pre_sample.characteristics,
                        derives_from=source,
                        comments=[Comment(name='created', value='Created with MtblsWs-Py')]
                        )
       isa_study.samples.append(sample)
       ...
I am using parts of a previous sample here just to ensure data is not the problem. I've also tried adding a whole process including source, sample, etc. to the study with similar results.

**Comment by djcomlab** [comment]
Thanks - your code looks good to me, so will look into this further, it sounds like a bug in the ISA-Tab writer to me.

**Comment by djcomlab** [comment]
Looks like this is a loading or dumping problem with `isatab.load()` or `isatab.dump()`, not a problem with appending the sample and then dumping the ISA-Tab. If I just load MTBLS10, and then dump with no modifications the extra Factor Value columns appear. 

Investigating further...

**Comment by djcomlab** [comment]
Yep, definitely buggy behaviour during parsing, adding the FVs multiple times. Should be fixed in `develop` branch now.

**Comment by jrmacias** [comment]
All right, I'll check it then.
Thanks a lot.

**Comment by djcomlab** [comment]
Fixed in `develop` branch, closing...
