### ISSUE TITLE
ParameterValue is not Commentable

### ISSUE THREAD

**Issue by jrmacias** [ISA-tools/isa-api#304]
Hi,
I think the class ParameterValue in isatools.model.py should inherit from Commentable as most of the other classes. In the attribute list (line 2351) seems like there should be comments, but they are not declared locally nor inherited:

class ParameterValue(object):
    """A ParameterValue represents the instance value of a ProtocolParameter,
    used in a Process.
    Attributes:
        category: A link to the relevant ProtocolParameter that the value is
            set for.
        value: The value of the parameter.
        unit: The qualifying unit classifier, if the value is numeric.
        comments: Comments associated with instances of this class.
    """

**Comment by djcomlab** [comment]
Hi @jrmacias, thanks for noticing this (not sure how I missed this as the docstring indicates it should be `Commentable`) - will update the model accordingly!

**Comment by djcomlab** [comment]
Fixed in `develop`, will be available in next release.
