### ISSUE TITLE
sra2isatab fails due to PKIX path building failed (Mac OSX only)

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#305]
This warning is raised during `sra2isatab.sra_to_isatab_batch_convert( ... )`:

```
Warning 
  FODC0002: I/O error reported by XML parser processing
  https://www.ebi.ac.uk/ena/data/view/SRA108974&display=xml:
  sun.security.validator.ValidatorException: PKIX path building failed:
  sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
  certification path to requested target
```
 and no ISA-Tab is generated.

Possibly related to https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html

**Comment by proccaserra** [comment]
Following discussion with @Zigur , add a statement to comply with saxon license, pointing to the source code.
