### ISSUE TITLE
Update to new version of pandas

### ISSUE THREAD

**Issue by nsadawi** [ISA-tools/isa-api#308]
Hi,
This is a request from NPC team https://github.com/phenomecentre/

Please update the requirement for a modern pandas basically because pandas 0.21-0.23 changed drastically .. currently it is still at 0.20

Test it with latest version and then change requirements.txt

Thank you

**Comment by djcomlab** [comment]
The reason the `pandas` version is fixed to `0.20` is due to issue in https://github.com/ISA-tools/isa-api/issues/266

**Comment by djcomlab** [comment]
Fixed in master.
