### ISSUE TITLE
Adding Comments to existing Person to a Study loaded fails to dump out

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#309]
Reported by MetaboLights (@jrmacias):

isatab.load()->add comments to person->isatab.dump() fails.

Fails when trying to add (or update) a contact with a different number of comments than the ones already in the study:

When add the new person with comments to a study where the rest of the contacts have no comments… fail.

When add the new person with comments to a study where the rest of the contacts actually have comments… there is no problem at all. Debug complain with:
```
File “/Users/.../.virtualenvs/MtblsWS-Py/lib/python3.5/site-packages/pandas/core/indexing.py”, line 439, in _setitem_with_indexer
   raise ValueError(“cannot set a row with ”
ValueError: cannot set a row with mismatched columns
```

Scenario 1: a study with on contact and no comments. When adding a new contact without comments, everything is all right. When adding a new contact with one (or more) comments, it fails.
Scenario 2: a study without contacts. When adding a new contact, it always go on well regarding the number of comments. When adding a second contact, it will fail if it has not the same number of comments than the previous one.

**Comment by djson8** [comment]
This is indeed a problem with indexing, as @jrmacias pointed out (via Slack).

It looks like the problem is because the Comments rendering currently expects all contacts to have the same set of Comment objects in order to serialize correctly.

**Comment by djcomlab** [comment]
This is indeed  problem with indexing, as @jrmacias pointed out (via Slack).

The problem is that the code expects every `Person` object to have the same `Comment` type (e.g. `Comment` object with same `.name`), but the example provided does not do this.
