### ISSUE TITLE
JSON to Tab conversion (v1)

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#31]

**Comment by agbeltran** [comment]
‘Label’ ('Labeled Extract Name') and ‘Material Type’ in tab2json conversion are map as characteristics (material attribute) to the corresponding material; the json2tab conversion needs to put them back as specific columns 'Label' and 'Material Type'

**Comment by djcomlab** [comment]
This now works with a test using BII-S-3. I'll leave this open while further testing is done on some of the other datasets.
