### ISSUE TITLE
Hash (#) in protocol text causes parsing issues

### ISSUE THREAD

**Issue by khaug** [ISA-tools/isa-api#323]
When a hash (#) is used in the protocol text, the ISA-API stops parsing the text

**Comment by proccaserra** [comment]
@khaug investigating -> probably caused by 
https://github.com/ISA-tools/isa-api/blob/master/isatools/isatab.py#L1159
used in
https://github.com/ISA-tools/isa-api/blob/master/isatools/isatab.py#L1234

but we need more dig into this. thx for reporting

**Comment by khaug** [comment]
Hi @proccaserra 
We are using isaoools 0.10.3.  

If the "Study Protocol Description" contains a hash, like here: ".....EDTA tube; Capillary Blood collection tube (RAM scientific Cat no.#077052).....". the rest of the row is not read. It stops at "Cat no."
