### ISSUE TITLE
Term Source from Study design descriptors not returned

### ISSUE THREAD

**Issue by khaug** [ISA-tools/isa-api#327]
Hi guys

Using isatools api 0.10.3 I am not able to read the term source from "study.design_descriptors". I can persist a new design descriptor, but we are not able to get the term_source (Study Design Type Term Source REF) back again using the API.

In the investigation file I have:
`Study Design Type	metabolomic profiling	metabolomic profiling2	metabolomic profiling3	metabolomic profiling4
Study Design Type Term Accession Number	http://www.ebi.ac.uk/efo/EFO_0000752	http://www.ebi.ac.uk/efo/EFO_0000752	http://www.ebi.ac.uk/efo/EFO_0000752	http://www.ebi.ac.uk/efo/EFO_0000752
Study Design Type Term Source REF	EFO	EFO2	EFO3	EFO4`

But using the API to read this, I see:
`[isatools.model.OntologyAnnotation(term='metabolomic profiling', term_source=None, term_accession='http://www.ebi.ac.uk/efo/EFO_0000752', comments=[]), isatools.model.OntologyAnnotation(term='metabolomic profiling2', term_source=None, term_accession='http://www.ebi.ac.uk/efo/EFO_0000752', comments=[]), isatools.model.OntologyAnnotation(term='metabolomic profiling3', term_source=None, term_accession='http://www.ebi.ac.uk/efo/EFO_0000752', comments=[]), isatools.model.OntologyAnnotation(term='metabolomic profiling4', term_source=None, term_accession='http://www.ebi.ac.uk/efo/EFO_0000752', comments=[])`

**Comment by khaug** [comment]
Looks like this is the OntologyAnnotation object, as we see it in other places as well. Are we persisting the data correctly I wonder?

**Comment by proccaserra** [comment]
Hi @khaug 
thx for reporting. Do you create the OntologySource first ?


obi = OntologySource(name='OBI', description="Ontology for Biomedical Investigations")
investigation.ontology_source_references.append(obi)

then:
intervention_design = OntologyAnnotation(term_source=obi)
intervention_design.term = "intervention design"
intervention_design.term_accession = "http://purl.obolibrary.org/obo/OBI_0000115"
study.design_descriptors.append(intervention_design)

or do you do only the following:
descriptor_1 = OntologyAnnotation(
                  term="<some term>", 
                  term_source="", 
                  term_accession="")

? 
thx

**Comment by khaug** [comment]
Thanks @proccaserra! It was the source missing. Sorry to waste your time.
