### ISSUE TITLE
ontology term serialisation issue from the create mode

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#338]
.pyenv/versions/3.6.5/envs/venv365/src/isatools/isatools/isajson.py in get_ontology_annotation(o)
   1566                     {
   1567                         "@id": id_gen(o),
-> 1568                         "annotationValue": o.term,
   1569                         "termAccession": o.term_accession,
   1570                         "termSource": o.term_source.name if o.term_source else None

AttributeError: 'str' object has no attribute 'term'

**Comment by proccaserra** [comment]
can be addressed without code alteration by using OntologyAnnotation objects instead of strings in the assay definitions. I'll document which bits need to be amended

**Comment by Zigur** [comment]
This has been solved with release  v0.12
