### ISSUE TITLE
Name of the (nano) material JSON schema

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#34]
As agreed, we are trying to develop a [JSON schema](https://github.com/enanomapper/isa-api/tree/master/isatools/schemas/isa_model_version_1_0_schemas/material), corresponding to the ISA-TAB-Nano material file.

Wondering what would be the appropriate file name, as  you already have schema named [material_schema.json](https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/core/material_schema.json) for the material nodes of the experimental graph.

**Comment by agbeltran** [comment]
Hi @vedina, what about nano_material_schema.json? Otherwise, doesn't the ISA-Tab nano spec suggest a name?

**Comment by agbeltran** [comment]
We thought about creating the extensions in separate folders under:
https://github.com/ISA-tools/isa-api/tree/master/isatools/schemas/isa_model_version_1_0_schemas
(where we also have the 'core' schemas)

Would that work for you?
Thanks

**Comment by vedina** [comment]
- ISA-TAB-Nano uses `i_material.txt` , hence we named the new schema [material_schema.json](https://github.com/enanomapper/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/material/material_schema.json) in a subfolder `material`.

However, in ISA there already is `material_schema.json`, describing quite a different object. I'm concerned having the same name for two different schema may confuse the parsers (if not people).

**Comment by agbeltran** [comment]
@vedina I still think it would be better to name the schema nano_material_schema.json - in the ISA model (and the schemas we have been working on), the concept of material is generic - then sources/samples are special cases (to be strict, they are material elements that play specific roles). The serialisation to a particular format (e.g. ISA-Tab nano) could use the required filename (i_material.txt) if needed. 

I will close the issue now, but @vedina or @proccaserra, do re-open it if you think this requires further discussion. 

Many thanks

**Comment by vedina** [comment]
We avoided naming it "nano", because what we are working on is rather generic way to describe the composition of chemical substances (with nanomaterial a special case).  Perhaps we should use "composition" in the schema name.

**Comment by agbeltran** [comment]
Actually, I think that @proccaserra was thinking along those same lines... We looked at 'composite material' but we found this: https://en.wikipedia.org/wiki/Composite_material

What about 'composition material'? would that work?

**Comment by vedina** [comment]
not sure it's the same (similar, yes). 

at the moment we need support for chemical substances (including nanomaterials), as per these definitons for example. 

[NPO chemical substance](http://bioportal.bioontology.org/ontologies/NPO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2Fnpo%23NPO_1973)

[More ontology definitions in BioPortal](http://bioportal.bioontology.org/search?utf8=%E2%9C%93&query=chemical+substance&commit=Search)
 
[IUPAC substance definition](http://goldbook.iupac.org/C01039.html)
````
Matter of constant composition best characterized by the entities (molecules, formula units, atoms) it is composed of. Physical properties such as density, refractive index, electric conductivity, melting point etc. characterize the chemical substance.
````


[REACH substance definition](https://echa.europa.eu/documents/10162/13643/nutshell_guidance_substance_en.pdf)
```
a chemical element and its compounds in the natural state or obtained by any
manufacturing process, including any additive necessary to preserve its stability and
any impurity deriving from the process used, but excluding any solvent which may be
separated without affecting the stability of the substance or changing its
composition
```

**Comment by proccaserra** [comment]
Hi @vedina, what about calling mcm_material_extension, where mcm would stand for 'mixture & complex molecular entity' for now. the name could be altered as the schema is created, which would clarify our appreciation of the envelop of cases it is supposed to support?

**Comment by vedina** [comment]
sounds good, thanks @proccaserra

**Comment by agbeltran** [comment]
Great! But maybe remove 'extension' from the name (as we know this won't be part of the core, and it will be in a separate folder for extensions)? so, it would be mcm_material_schema.json.

**Comment by vedina** [comment]
Done https://github.com/enanomapper/isa-api/commit/e32a213323692478126ce221b468d891abce23d8

**Comment by agbeltran** [comment]
Thanks @vedina, send us a pull request when you are ready (do consider that we have been pushing many updates to our repo).

**Comment by vedina** [comment]
we try to merge with yours, will send a pull request when ready.
