### ISSUE TITLE
consistency of schema keys and implementation: 

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#343]
annotationValue vs .term
- [ ]  isa-api/isatools/resources/schemas/isa_model_version_1_0_schemas/core/ontology_annotation_schema.json

picked up during development of isa study_design schema:
../datascriptor/study-design-json-schemas/blob/master/ontology_annotation_schema.json

**Comment by Zigur** [comment]
Review this further:
- [ ] evaluate whether to replace "term" with "annotationValue" in the ISA study design JSON serialisation. 
- [ ] evaluate whether to replace "term" with "annotationValue" in the assay template configuration

**Comment by Zigur** [comment]
The ISA study design JSON serialisation has been superseded by the datascriptor study design JSON representation. Hence, this replacement of "term" with "annotationValue" is not needed anymore at this stage.
