### ISSUE TITLE
Add 'Phenotyping' to the supported protocol type list for MIAPPE compliance

### ISSUE THREAD

**Issue by bedroesb** [ISA-tools/isa-api#345]
Because 'Phenotyping' is not a supported protocol, we are forced to use 'nucleic acid sequencing' as protocol_type to have an assay name column in the assay file.

https://github.com/ISA-tools/isa-api/blob/ee60fd53e61e0ecfa92f3a0a0954f6fd3032f832/isatools/isatab.py#L1409

**Comment by proccaserra** [comment]
done in 0.12

**Comment by bedroesb** [comment]
will have to update plant brapi 2 isa now ;)

**Comment by bedroesb** [comment]
@proccaserra  I can confirm this works
