### ISSUE TITLE
Parameter Units not displayed in Study File

### ISSUE THREAD

**Issue by Thyra** [ISA-tools/isa-api#347]
When adding Parameter Values to processes, their value is displayed in the generated study file but not the unit. Here's a minimum working example:
```python
from isatools.model import *
i = Investigation()
s = Study(filename="s_study.txt")
i.studies.append(s)

p = Protocol(name="myProtocol")
s.protocols.append(p)
parameter = ProtocolParameter(parameter_name=OntologyAnnotation(term="myParameter"))
p.parameters.append(parameter)

source = Source(name="Source")
sample = Sample(name="Sample", derives_from=[source])
s.sources.append(source)
s.samples.append(sample)

proc = Process(executes_protocol=p)
proc.inputs.append(source)
proc.outputs.append(sample)
s.process_sequence.append(proc)

proc.parameter_values.append(
    ParameterValue(category=parameter, value=OntologyAnnotation(term="12"), unit=OntologyAnnotation(term="m"))
)

from isatools import isatab
print(isatab.dumps(i))
```

The resulting study file looks like this:
```
Source Name	Protocol REF	Parameter Value[myParameter]	Sample Name
Source	myProtocol	12	Sample
```

I'm using isatools in version 0.10.3. Is this a bug or am I doing something wrong? My actual use case is a bit more complex with many more protocols and parameters including ontology references but it seems the problem also lies in this simple example.

**Comment by Thyra** [comment]
This is still the case when using the latest commit on the master branch (ee60fd5) instead of version 0.10.3.

**Comment by proccaserra** [comment]
@Thyra, thx for reaching out. 

@Zigur  The problem comes from the following:

```python
proc.parameter_values.append(
    ParameterValue(category=parameter, value=OntologyAnnotation(term="12"), unit=OntologyAnnotation(term="m"))
)
```

when it should be:

```python
proc.parameter_values.append(
    ParameterValue(category=parameter, value=12, unit=OntologyAnnotation(term="m"))
)
```

Note that when the intent is to report a `quantitative value`, the ISA object does not expect to get an ```ontology annotation``` or a ```string```. The problem is that we are not catching that and reporting it properly. 

Thanks for reporting.

**Comment by Thyra** [comment]
@proccaserra That's already very helpful, thank you! Is there any other documentation than https://isatools.readthedocs.io/ where I could read about these things?

**Comment by proccaserra** [comment]
@Thyra there will be soon as I am updating the isareadthedoc and various Jupyter notebooks for the new release. so please bear with us.

Out of curiosity: could you tell us which project you are working on ? It's great to hear about our users and we could add you to our pages. thx

**Comment by Thyra** [comment]
OK, I'm looking forward to it! :-)

Of course; I'm preparing data from a phenotyping experiment for publication and want to describe it in compliance with the [_Minimum Information About a Plant Phenotyping Experiment_  standard](https://www.miappe.org/) which is [implemented](https://github.com/MIAPPE/MIAPPE/blob/master/MIAPPE_Checklist-Data-Model-v1.1/MIAPPE_mapping/MIAPPE_Checklist-1.1-with-mapping.pdf) in ISATab. As soon as the dataset and the accompanying paper are out I'd be happy to share my code as well, if there's enough interest and time I might even turn it into a generalized tool to help people create MIAPPE-compliant isa-tab descriptions for their own datasets.  
I'm currently working at the [IPK](https://www.ipk-gatersleben.de/index.php?id=1&L=1) which publishes their phenotyping data at the [PGP](https://edal-pgp.ipk-gatersleben.de/) (such as [this dataset](https://doi.ipk-gatersleben.de/DOI/0500df3a-3cf8-44e7-b3ee-51a34ef0afb4/4688d22f-5853-4b40-b091-df465f01ee25/2/1847940088)). If you'd like to put us on your website best get in touch with [Daniel Arend](https://www.ipk-gatersleben.de/en/breeding-research/bioinformatics-and-information-technology/staff/), I just started working here last week and don't really know the whole setup/background yet ;-)
