### ISSUE TITLE
Handling quantitative fields in FactorValues (and possibly OntologyAnnotation and Chars)

### ISSUE THREAD

**Issue by Zigur** [ISA-tools/isa-api#352]
We must make sure that:

- if a unit is provided, the value must be a number
- if a new value is being set and a unit is present, the new value must be a number 
- if a new unit is being set, we must verify that the current value is a number

**Comment by Zigur** [comment]
Check if this is fully covered and tested

**Comment by proccaserra** [comment]
pro: a stronger typing would allow better validation and calculation
cons: would prevent data entry if users want to supply summary stats, intervals (e.g. 22-50 year old)
