### ISSUE TITLE
Writing big study/assay files

### ISSUE THREAD

**Issue by Thyra** [ISA-tools/isa-api#353]
Good morning!
I'm writing very big assay files (> 10,000 rows) and slowly the performance is becoming noticeable (it took 1 min for 5,000 rows and about 3.5 mins for 10,000 rows on my machine). Is there anything I should pay attention to to make rendering/writing the files as fast as possible? Of course 3.5 mins is not really a problem yet but the files may get much bigger and I want to be prepared ;-).

On a related note: I'm working on a small Java Library to write ISA-Tab files (we'll push it to GitHub early next week) that tries to circumvent this by iteratively creating the objects and flushing them out into the file, and I'm also asking because I'd like to do some tests whether that actually has any noticeable effect on performance. Of course the Java Library has a lot less features and flexibility than isatools but we're hoping it will make ISA-Tab available to people with no experience in python and/or who want to integrate an ISA-Tab export into their existing Java applications, so we thought it might still be worth sharing with the community :-)

**Comment by proccaserra** [comment]
Hi @Thyra. Thx for heads up and great stuff wrt the Java library. Going back to your first question, I was wondering if you could send us (email to the isatools list)  a sample of your output (maybe 100 rows). I'd like to check the overall structure to see where things could be improve, check s_study and a_assay files. From our own tests, we know that heavy branching in the workflows followed by pooling and branching again can slow things down.

**Comment by Thyra** [comment]
Thank you, I just sent an email to isatools@googlegroups.com.

**Comment by Zigur** [comment]
At the moment the entire `process` object is used as a node in the process graph of `networkx`. This slows things considerably.
We need  to:
- [ ] replace the whole object with an identifier
- [ ] check that existing code still function
- [ ] verify backward compatibility

**Comment by terazus** [comment]
Done
