### ISSUE TITLE
Characteristics of Sources appear in Samples list of generated JSON

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#36]
I've noticed that Characteristics[] that appear in the Sources section of study ISAtab files appear in the characteristics of samples after the isatab2json conversion.

I am unsure if this is normal behaviour, as the samples list in the study tab files do not repeat these. Do samples inherit source characteristics?

**Comment by agbeltran** [comment]
I think this is indeed a bug. Are you seeing it in BII-I-1.json? Can you point me to the study? Or do you see it in both.

**Comment by agbeltran** [comment]
To investigate further, you can have a look at createSourcesDictionary and createSampleDictionary methods. It would be necessary to check the study.nodes to check that what is coming from the parser is correct.

**Comment by djcomlab** [comment]
Yes, this is in BII-I-1.json that the characateristics for the studies appear in both sources and samples.

Inside s_BII-S-1.txt I see the characteristics appear in the sources section only.

**Comment by agbeltran** [comment]
This is fixed now.
