### ISSUE TITLE
isaTools/Model/Comment raises ISAModelAttributeError when setting comment value with valid value

### ISSUE THREAD

**Issue by podonnellalidyne** [ISA-tools/isa-api#360]
While implementing some code to set the value of a comment, we would receive an ISAModelAttributeError, even when passing in a valid string.  The value is set even though the error is raised.  Catching and discarding the Error allows the code to complete and function normally.

Upon inspecting the code, it appears that the @value.setter in isatools/model.py has the raise Error as the last statement of the method instead of in an else statement, as seen in @name.setter.

```
@value.setter
    def value(self, val):
        if isinstance(val, str):
            self.__value = val
        raise ISAModelAttributeError('Comment.value must be a string')
```

should be

```
@value.setter
    def value(self, val):
        if isinstance(val, str):
            self.__value = val
        else:
            raise ISAModelAttributeError('Comment.value must be a string')
```

**Comment by proccaserra** [comment]
@podonnellalidyne tx for reporting.

**Comment by Zigur** [comment]
This should be solve now with commit 15f33c7adaa4ec0ad24e67a35a67ad46a53849c0
