### ISSUE TITLE
Unpopulated objects appear in generated JSON

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#37]
When generating JSON using istab2json for BII-I-1, there's several instances where objects appear but have not values in the properties. For example, under protocols, a few components and parameters appear with one component or parameter object but all set to empty strings.

Also for every process listed under processSequence in the assays list.

**Comment by agbeltran** [comment]
Yes, this is related to unfinished #15 and need to modify the parser (#38).

**Comment by djcomlab** [comment]
This has been addressed/fixed, right?

**Comment by agbeltran** [comment]
yes! closing...
