### ISSUE TITLE
create a helper function to show users current ISA Protocol.type values

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#372]
- [x] to create a document consolidating all the ‘hard coded’ strings in ISA-API (mostly protocol.type.term ) 

protocol type required strings | hard requirement in the ISA-API |  
-- | -- | --
Source Name -> Sample Name | sample collection | http://purl.obolibrary.org/obo/OBI_0000659
Sample Name -> Extract Name | extraction | http://purl.obolibrary.org/obo/OBI_0302884
Extract Name -> Labeled Extract Name | labeling | http://purl.obolibrary.org/obo/OBI_0600038
<Material Name> -> Assay Name | phenotyping |  
Labeled Extract Name -> Assay Name | library sequencing(*) | http://purl.obolibrary.org/obo/OBI_0600047
<Material Name> -> MS Assay Name | mass spectrometry | http://purl.obolibrary.org/obo/OBI_0000470
<Material Name> -> NMR  Assay Name | nmr spectroscopy | http://purl.obolibrary.org/obo/OBI_0000623
<Material Name> -> Hybridization Assay Name | nucleic acid hydridization | http://purl.obolibrary.org/obo/OBI_0302903
<Material Name> -> Assay Name | data acquisition | http://purl.obolibrary.org/obo/OBI_0600013
<Assay Name> -> Data Transformation Name | data transformation | http://purl.obolibrary.org/obo/OBI_0200000
<Assay Name> -> Data Transformation Name | normalization | http://purl.obolibrary.org/obo/OBI_0200169
<Assay Name> -> Data Transformation Name | metabolite identification | http://purl.obolibrary.org/obo/MI_2131
<Assay Name> -> Data Transformation Name | protein identification |  

(*) should probaby be 'nucleic acid sequencing' see [issue #371](https://github.com/ISA-tools/isa-api/issues/371)

- [x] to create a data structure to hold synonyms of ISA protocol type (sometimes aligned with ISA assay technology type) 
- [x] to create a helper method attached to ISA Protocol object to prompt users values used by the ISA-API require

**Comment by Zigur** [comment]
The static method `Protocol.show_allowed_protocol_types()` now allows to pretty print to stdout the list of allowed/recommended protocol types taken from the YAML file (that now includes all the protocols listed in the table above.)

If there are outstanding points, this can be reopened. Closing for now
