### ISSUE TITLE
Message printed out on import

### ISSUE THREAD

**Issue by Zigur** [ISA-tools/isa-api#374]
When the core isa model objects are loaded, e.g.:

```
from isatools.model import Investigation, Study
```

These two strings are printed out:
```
LOG: <Logger isatools (DEBUG)>
/Users/massi/.pyenv/versions/3.7.5/envs/isa-create-notebook-3.7.5/src/isatools/isatools/net/resources/saxon9/saxon9he.jar
```

See also the screenshot below.

<img width="787" alt="Screenshot 2020-11-18 at 19 13 24" src="https://user-images.githubusercontent.com/6864177/99577269-01cd4480-29d3-11eb-8924-7dd633063c93.png">

These should be removed before the new issue is released, but I have serious issues in finding where they could be as they are not in the `isatools/model.py` file. DO you have any suggestion on this @proccaserra ?

**Comment by Zigur** [comment]
The second logging message should be removed now. The `LOG: <Logger isatools (DEBUG)>` message still has to be found

**Comment by proccaserra** [comment]
@Zigur yes most probably coming from those print statements i left in biocrates2isa.py.

**Comment by Zigur** [comment]
The `LOG: <Logger isatools (DEBUG)>` message was in `isatools/magetab.py`, now removed
