### ISSUE TITLE
All UUID created during Model.py/OntologyAnnotation.__init__() are duplicates

### ISSUE THREAD

**Issue by podonnellalidyne** [ISA-tools/isa-api#381]
While parsing isaTab to isaJson, ontologies loaded into the OntologyAnnotation Class have the same @id value

This is because the _id method parameter is only evaluated once in python, so it creates a single uuid.uuid4() that is set to all ontologies as the @id param, unless a new id_ param is passed in.  passing in _id = none and then setting the variable to  uuid4() if the method param is None fixes this issue.  However if then something were passed in in the _id value, all future id_ fields would have that same passed in value, as the optional variable reference would no longer point to None.

Currently:
```
def __init__(self, term='', term_source=None, term_accession='',
                 comments=None, id_=str(uuid.uuid4())) :
        super().__init__(comments)
        self.__term = term
        self.__term_source = term_source
        self.__term_accession = term_accession
        self.id = id_
```

This fixes then issue
```
def __init__(self, term='', term_source=None, term_accession='',
                 comments=None, id_ = None) :
        super().__init__(comments)
        self.__term = term
        self.__term_source = term_source
        self.__term_accession = term_accession
        self.id = str(uuid.uuid4()) if not id_ else id_

```

Ideally because of the way python evaluates these optional params, maybe the _id param should be required, and evaluates to something every time, or should be removed from __init__() and can be set after the fact, to ensure there are no inadvertent duplicate values.

**Comment by Zigur** [comment]
Thanks for noticing this @podonnellalidyne. We'll be fixing the code accordingly and include this bugfix into the next release.
