### ISSUE TITLE
Invalid JSON in isa_study_design_element_schema.json

### ISSUE THREAD

**Issue by jake-emerson** [ISA-tools/isa-api#388]
The JSON schema located here: 

    https://github.com/ISA-tools/isa-api/blob/master/isatools/resources/schemas/isa_study_design_model_0_1_schemas/isa_study_design_element_schema.json

is missing a closing curly brace. Parsers complain that the "properties.factorValues.type" key is duplicated, but this is still valid in the JSON spec.

**Comment by Zigur** [comment]
Thanks a lot, @jake-emerson. Those particular schemas are being superseded by [these](https://gitlab.com/datascriptor/study-design-json-schemas), but we'll double-check them against the current version 0.12 before moving them here.

**Comment by jake-emerson** [comment]
Thank you for pointing me there @Zigur . I'll take a closer look at your more recent work in GitLab. At the Jackson Laboratory we are working on a project where we are closely following the ISA model. It would be cool if we could connect at some point.

**Comment by proccaserra** [comment]
@jake-emerson happy to organise a call to follow-up and have and discuss some details about customisation options and features.

**Comment by proccaserra** [comment]
- [ ] migrate latest `ISA study design schemas` from gitlab to isa-api github repo
- [ ] add tests validating `ISA study design JSON instance` files against the `ISA study design schemas`
- [ ] update documentation about this
