### ISSUE TITLE
Data file pointers

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#39]
Is it possible to extend the [examples](https://github.com/ISA-tools/isa-api/tree/develop/isatools/sampledata) to include data objects with file names.  It's not clear at the moment where one should specify the data file names in the data object.

Also, I've noticed the BII-I-1 JSON examples include pointers to tab delimited files (`i_*.txt`, `s_*.txt` , `a_*.txt`), while all the metadata from these files should already be in the JSON itself.

**Comment by agbeltran** [comment]
Hi @vedina, we decided to include the pointers to tab delimited files to support tab to json to tab conversion. Those files won't be relevant for isa-json that is produced without an initial tab file.

**Comment by vedina** [comment]
Thanks @agbeltran, makes sense indeed.

**Comment by agbeltran** [comment]
Hi @vedina 

The examples now include all the information on data files produced by the experiment (see dataFiles, e.g. in [BII-I-1.json](https://github.com/ISA-tools/isa-api/blob/develop/isatools/sampledata/BII-I-1.json).

Thanks
