### ISSUE TITLE
write_assay_table_files not working

### ISSUE THREAD

**Issue by casper937** [ISA-tools/isa-api#392]
When dumping a few existing, unmodified example studies retrieved from Metabolights (MBTLS1410, MTBLS1437, MTBLS1080), an error is given:
isatab.py(write_assay_table_files:1383) >> No paths found, skipping writing assay file. 
This possibly the cause of something in the function _all_end_to_pathts(). 

Any help for this would be very much appreciated.

**Comment by proccaserra** [comment]
@casper937 a couple of questions: 

- [ ] how do you dump those files? ie which version of the isa-api are you using?
- [ ] in my hands, those MTBLS archives fail validation and cannot be read due the missing Protocol Parameters.
- [ ] can you provide us with some context about your usage of the isa files (e.g which projects?).

bw.

**Comment by casper937** [comment]
I use isatab.dum(Investigation, output_dir) to dump the files. I have installed is-api two weeks ago, from source (github).
I want to create a pipeline for generating isa-tab files. I used to these MTBLS-files to test the package.

**Comment by proccaserra** [comment]
@casper937  I have tracked down the issue with not well formed ISA document. I have contacted Metabolights to make them aware of the issue. This is the same issue for MTBLS1401 and 1437 (ie absence of ISA nodes for Extract Name, Labeled Extract Name while assigning attributes to these objects.

Do you want to have a call to discuss your pipeline?

**Comment by casper937** [comment]
Thanks very much! My pipeline is very early in development. I don't think a call would be helpful right now. But I appreciate the offer.

**Comment by casper937** [comment]
Question: is this issue specific for these MTBLS studies, or is it related to the requirements of Metabolights itself?
