### ISSUE TITLE
Study filenames missing from conversion to JSON

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#40]
Currently the study filename properties are missing from the tab2json conversions.

Are already aware of this as was due to previous changes, and will need to reintroduce to allow more accurate conversions back to ISAtab from JSON.

**Comment by agbeltran** [comment]
Thanks @djcomlab. I have just added it and pushed it. We can merge it anyway. Please, do take care of other issues you may find as I will be offline for a while. Thanks.

**Comment by agbeltran** [comment]
I pushed the changes to feat/conversion. See if you can merge them into develop. Thanks
