### ISSUE TITLE
Characteristic category and Factor Value factor names missing in JSON schemas and tab2json conversion

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#41]
For each Characteristic or Factor Value, there is an additional typing that is not currently present in the schemas.

Example in BII-I-1 tabular:

Characteristics[organism] column is present, but 'organism' part is lost in conversion.
Factor Value[limiting nutrient] column is present, but 'limiting nutrient' part is lost in conversion.

I've already done some work in the isatab package loader to parse these into model objects, so it will probably be straightforward to modify the JSON schemas and tab2json converter to fix this.

**Comment by agbeltran** [comment]
These are now defined as 'categories' within the schemas for factors/characteristics/parameters: https://github.com/ISA-tools/isa-api/tree/develop/isatools/schemas/isa_model_version_1_0_schemas/core
