### ISSUE TITLE
Parameters in the process schema

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#42]
Could you clarify, the `parameters_schema.json` consists only of ontology annotation (parameterType) and unit, not sure where numeric values should be stored.

**Comment by proccaserra** [comment]
Hi Nina,

I guess you are referring to the following schema "protocol_parameter_schema.json"?

{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title" : "ISA protocol parameter schema",
    "description" : "JSON-schema representing a parameter for a protocol in the ISA model",
    "type" : "object",
    "properties" : {
        "parameterName": {
            "$ref": "ontology_annotation_schema.json#"
        },
        "unit": {
             "$ref": "ontology_annotation_schema.json#"
        }
    },
    "additionalProperties": false
}

This is used to declare parameters names when creating a protocol. The values for those parameters are not declared (at least in ISA 1.0) as it does not allow to set default values.

Values will be reported using:
https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/core/process_parameter_value_schema.json

{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title" : "ISA process parameter value schema",
    "description" : "JSON-schema representing a Parameter Value (associated with a Protocol REF) in the ISA model",
    "type" : "object",
    "properties" : {
        "value" : { "type" : "string"}
    },
    "additionalProperties": false
}

Here , I'd would say that it seems something is missing and should be closer to what can be found in ISA material attribute schema :

{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title" : "ISA material attribute schema",
    "description" : "JSON-schema representing a material attribute or characteristic in the ISA model",
    "type" : "object",
    "properties" : {
        "value": {
            "anyOf" : [
                { "$ref": "ontology_annotation_schema.json#"},
                { "type": "string"},
                { "type": "number"}
                ]
        },
        "unit": {
            "$ref": "ontology_annotation_schema.json#"
        }
    },
    "additionalProperties": false
}

@agbeltran , @djcomlab , any comments?

**Comment by vedina** [comment]
@proccaserra thanks. 

Then perhaps the [process schema](https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/core/process_schema.json)  should refer to [process_parameter_value_schema.json](https://github.com/ISA-tools/isa-api/blob/master/isatools/schemas/isa_model_version_1_0_schemas/core/process_parameter_value_schema.json) as well ?  As at the moment we could not find how to specify parameter values .

**Comment by agbeltran** [comment]
Hi @vedina, yes, we already included this, but it is in the develop branch:

https://github.com/ISA-tools/isa-api/blob/develop/isatools/schemas/isa_model_version_1_0_schemas/core/process_schema.json

**Comment by agbeltran** [comment]
@vedina 

so, we have a [protocol_parameter_schema.json](https://github.com/ISA-tools/isa-api/blob/develop/isatools/schemas/isa_model_version_1_0_schemas/core/protocol_parameter_schema.json) and a [process_parameter_value_schema.json](https://github.com/ISA-tools/isa-api/blob/develop/isatools/schemas/isa_model_version_1_0_schemas/core/process_parameter_value_schema.json) where the numeric values can be represented.

Do let us know if there is any issue with this in your view. Thanks
