### ISSUE TITLE
utf-8 encoded json fails UTF-8 check

### ISSUE THREAD

**Issue by rabuono** [ISA-tools/isa-api#421]
I have an investigation.json file that I made and saved using VS Code
<details>
  <summary>VS code version</summary>

> Version: 1.60.2 (system setup)
> Commit: 7f6ab5485bbc008386c4386d08766667e155244e
> Date: 2021-09-22T12:00:31.514Z
> Electron: 13.1.8
> Chrome: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19042

</details>
When running:

> from isatools import isajson
my_json_report = isajson.validate(open('investigation.json'))

I get:

> 2021-10-12 16:02:15,788 [INFO]: isajson.py(validate:1371) >> ISA JSON Validator from ISA tools API v0.3
2021-10-12 16:02:15,788 [INFO]: isajson.py(validate:1380) >> Checking if encoding is UTF8
2021-10-12 16:02:16,314 [WARNING]: isajson.py(check_utf8:971) >> (W) File should be UTF-8 encoding but found it is 'utf-8' encoding with 0.7525 confidence
2021-10-12 16:02:16,315 [CRITICAL]: isajson.py(validate:1486) >> (F) Something went very very wrong! :(

My file seems to be recognized as `utf-8` instead of `UTF-8` and that seems sufficient for the validation to fail.
This seems due to the following line:
https://github.com/ISA-tools/isa-api/blob/0e934efcc32b13166a3808ec3373116078e47912/isatools/isajson.py#L989

If I change the line to accept `utf-8` the file passes validation.
Should the `UTF-8` check be case sensitive?

**Comment by terazus** [comment]
Fixed
