### ISSUE TITLE
usage/installation on Mac M1 chip

### ISSUE THREAD

**Issue by ghaggart** [ISA-tools/isa-api#451]
I'm having trouble installing isatools on the Apple Silicon M1 chip using miniconda and pip. The reason is that the universal wheels for various packages were released in versions that are not supported by isatools - the main issue I've found is numpy and pandas. 

Can you provide support for the latest versions of numpy and pandas?

Thanks!

**Comment by proccaserra** [comment]
@ghaggart sorry for the delay in getting back to you. We will be investigating the issue and prepare an update.

**Comment by terazus** [comment]
@ghaggart we have prepared an update of pandas and numpy on master. We will be preparing a release soon. I suggest trying to install from the master branch in the meantime.

**Comment by ghaggart** [comment]
Thank you for doing this!
