### ISSUE TITLE
Wikidata namespace(s)

### ISSUE THREAD

**Issue by egonw** [ISA-tools/isa-api#481]
Currently, the profiles have:

https://github.com/ISA-tools/isa-api/blob/6a5a5302ee621c5d49368cc0aacde531953d36f4/isatools/resources/json-context/wdt/isa_material_attribute_wdt_context.jsonld#L4-L5

The IRI for a Wikidata item looks like `http://www.wikidata.org/entity/Q221653` (for Utrecht University). If Wikidata items are used as term, then the profile should use the namespace `http://www.wikidata.org/entity/`, which Wikidata itself links to the prefix `wd`.

I am not sure how the property namespace is intended to use, but commonly Wikidata properties have an associated Wikidata item linked to is. For example, the property `http://www.wikidata.org/entity/P231` (or the `owl:ObjectProperty` `http://www.wikidata.org/prop/P231`) has the matching item `https://www.wikidata.org/entity/Q102507`. 

cc @andrawaag

**Comment by terazus** [comment]
This should now be fixed with the https://github.com/ISA-tools/isa-api/commit/3243b77171639029fb0c7b90cfcb646f89fbde42
