### ISSUE TITLE
Unable to install isatools due to PyYAML build failure

### ISSUE THREAD

**Issue by JeremyLeland** [ISA-tools/isa-api#498]
I tried installing isatools today via pip and hit build errors in the PyYAML dependency.

I'm seeing many apps that use PyYAML breaking recently after a new release of Cython, see: https://github.com/yaml/pyyaml/issues/601. It looks like a temporary fix for this was released as PyYAML 6.0.1: https://github.com/yaml/pyyaml/pull/702

This project is explicitly depending on PyYAML~=5.4.1. Is the project able to use PyYAML 6.0.1?

**Comment by jake-emerson** [comment]
Another (temporary) option is to allow PyYAML version 5.3.1. See: https://github.com/yaml/pyyaml/issues/601#issuecomment-1712822411

**Comment by jlbales** [comment]
I am also having this issue. Is there a workaround for this?

**Comment by jake-emerson** [comment]
Hi all. Same issue here. Moving back to 5.3.1 does seem to work, but also has a security issue: https://security.snyk.io/vuln/SNYK-PYTHON-PYYAML-590151.

**Comment by proccaserra** [comment]
Hi all, apologies to the delay. 
fixed in master 
will work on a release asap
