### ISSUE TITLE
Incorporate ISA default configurations in ISA object creation functionality

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#51]
Related to #9 and #11

**Comment by agbeltran** [comment]
e.g. for microarray technology:

"Protocol REF"	"Hybridization Assay Name"	"Array Design REF"

Protocol REF value -> goes into executes protocol
Hybridization Assay Name -> it let us decide the uniqueness of the process 
Array Design REF -> corresponds to parameter in the process

**Comment by proccaserra** [comment]
Just checked ISA-default configuration against our current ISA1.0 json schema for ISA fields found in ISA configurations which may warrant refinement. I list those fields headers below, with their context:

-"Label" field: follows a 'Labeled Extract Name" field, used to specify a dye (biotin) or compound (p33, iTRAQ reagent), found in Microarray and Mass Spectrometry applications. -> akin to a specialized 'Characteristics[] ' field.

-"Array Design REF": found in all configurations using 'DNA microarray" as 'technology type". Found *after* the 'Hybridization Assay Name" field header and used to specify the name of the microarray chip  (.e.g. Affymetrix HG_H133_2.0 or Agilent A4218). Can be cast as a 'Parameter Value[array design]' associated with a Process referencing a  protocol of type 'hybridization'.

Important Note: this element could be generalised to allow for the reference of an external list used in assays (e.g. targeted profiling assay such as Luminex or Biocrates Applications, where a predefined set of molecules are quantified or checked for presence in a sample).

-"Acquisition Parameter Data File": found in all configurations using NMR spectroscopy as 'technology type'. This is can be cast as a 'parameter value' associated with  a Process referencing a  protocol of type 'data acquisition'.


-other Data Files:  
for microarray -Array Data File ,(Raw Data File), -[Array Data Matrix File,-Derived Array Data File
-Derived Array Data Matrix File] (Derived Data File)

for 'metabolite profiling' and 'mass spectrometry' or 'nmr spectroscopy': 'Metabolite Assignment File' and 'Mass Isopotomer Distribution File' should be valid subtypes of 'Derived Data File'

Scan Name:
Found in 'DNA microarray' specific ISA configuration. The field is meant to track specific data acquisition event . in 95% of times, there is a 1-to-1 correspondant between 'Hybridization Assay Name' and Scan Name. however, one should bear in mind that the 'hybridization' event and the 'scanning event/data acquisition' are distinct processes. one hybridized microarray chip may be scanned repeatedly (in case of multiplexing) or for technical replication of data acquisition (not frequent  owing to photobleaching process which can take place). Map 'Scan Name' to a Process referencing a  protocol of type 'data acquisition'.

**Comment by proccaserra** [comment]
Related to #112 but not completed -> set status to stale
