### ISSUE TITLE
Incorporate sra xslt conversion

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#54]

**Comment by proccaserra** [comment]
documenting this issue a bit more:
i. dependency: saxon-9ee.jar [http://saxon.sourceforge.net/] for which we may need to get a license unless saxon-9he is good enough.
ii. input is a valid European Nucleotide Archive *Submission* accession number in the form of S?ERA\d+[6] (ERA148766 or  SRA148766) or a valid European Nucleotide Archie *Project* access number (ERP/SRP\d+[6]). this may require switching betwee 2 slightly different xsl stylesheets.
iii. support batch processing (input of a list of such accession number).
iv. error catching: we are aware of some intermittent bug with the ENA REST service and tokenization of ENA experiment references. @djcomlab had a suggestion on how to deal with this -> need to catch up
v. watch out for very large experiments (e.g rice genome experiment has 3500 records)

**Comment by djcomlab** [comment]
I thought the bug was something on the ENA side and was fixed??

Another thought - if possible, we should try not use SAXON (as this is Java dependent stuff). Python has a XSLT processor already, worth testing that first before introducing another legacy dependency.

**Comment by proccaserra** [comment]
good call @djcomlab but I thought python was lacking for xslt 2.0 support (http://stackoverflow.com/questions/29443364/use-saxon-with-python).

**Comment by djcomlab** [comment]
Maybe, but worth checking!

**Comment by djcomlab** [comment]
If not, @Zigur have a look at https://github.com/ISA-tools/isa-api/blob/master/isatools/convert/isatab2sra.py to see how I hooked into command line execution from Python to use the tab to SRA converter Java code. May be easier to wrap up the command in a shell script.
