### ISSUE TITLE
Define object where factor values are attached to

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#56]
currently, only to samples

**Comment by agbeltran** [comment]
This will be revisited when analysing query use cases and their performance. E.g. get all the raw data files corresponding to a specific factor value combination (which requires traversal at the moment).

**Comment by agbeltran** [comment]
We decided to attach them to the data files. Closing this issue and opening another one for that purpose.

**Comment by proccaserra** [comment]
@Zigur  to review code
@proccaserra produce test files + test serialization & document to refine the requirements
