### ISSUE TITLE
ideally-canonical.json invalid JSON

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#59]
ideally-canonical.json is not valid-formed JSON, so does not load in the Python JSON parser. Need to take care to run it through a validator before committing.

**Comment by proccaserra** [comment]
oxygen does not report any error regarding structure. do you have more information about the error (line number?).ta

**Comment by agbeltran** [comment]
@proccaserra the issue is when validating against the schemas; it will require an update to the file.

**Comment by djcomlab** [comment]
No, the issue is not against the schemas (well, perhaps it is also but this is not this issue), the problem is that is it not valid-formed JSON. json.load('ideally-canonical.json') fails.

@proccaserra Try JSONLint (www.jsonlint.com) for debugging. It gives the following error:

```
Error: Parse error on line 185:
...ersion": "2.0"		}, ],		"people": [{		
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got ']'
```

**Comment by djcomlab** [comment]
Confirm is fixed, closing.
