### ISSUE TITLE
ISA JSON schemas for create mode

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#6]

**Comment by agbeltran** [comment]
This ticket refers to creating the JSON schemas for the objects used in the create mode (e.g. SamplePlan, AssayPlan, etc.)

**Comment by djcomlab** [comment]
Check this for experimental design test examples:

https://github.com/ISA-tools/isa-api/blob/feat/create/isatools/create/test-examples.txt

**Comment by djcomlab** [comment]
Serialize treatment sequence in full, and summarise back to treatment plan elements
