### ISSUE TITLE
Consider characteristics with ontology annotations

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#60]
We need ISA-Tab example datasets

**Comment by proccaserra** [comment]
- matters only for ISA-Tab serialisation:
- ISA object creation supports characteristics.categories to be ontologyAnnotations.
- JSON serialization keeps this information
- Tab serialization does not -> ontologyAnnotation.category.term_url is lost 
How to address this by reforming ISA-Tab serialization? use curies and pattern like `term.curie' bearing in mind parsing problem with separator such '.' '[]], '()' in the field header of the table
