### ISSUE TITLE
Refactor unit declarations

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#61]

**Comment by agbeltran** [comment]
Analysing this issue, the units at the moment appear as:

       "unit": {
            "$ref": "ontology_annotation_schema.json#"
        }
 
in factor_value_schema, material_attribute_value_schema and process_parameter_value_schema.
Given that they are ontology annotations, they will have annotationValue and termSource and termAccession.

Compiling all the unit definitions at the study and assay level would mean referencing them from the value declarations. This would make the representation more compact (and opaque with the use of identifiers) but also might mean in some cases creating @id to what would be already URIs (if the termAccession/termSource is provided). 

So, I am not sure it would be good to actually make this refactoring.

Thoughts? @proccaserra @djcomlab @Zigur ?

**Comment by djcomlab** [comment]
I think it it's OK for @id to reference stuff that may already have URIs since it's only for internal use. Also, there's no guarantee a termAccession/termSource will be provided for a unit.
