### ISSUE TITLE
Typo in assay_schema.json

### ISSUE THREAD

**Issue by ntk73** [ISA-tools/isa-api#63]
"charactersitics": {
      "description": "List of all the characteristics (or material attributes) defined in the study, used to avoid duplication of their declaration when each material_attribute_value is created. ",
      "type": "array",
      "items": {
        "$ref": "material_attribute_schema.json#"
      }
    },

The attribute must be "characteristics" instead of "charactersitics"

**Comment by agbeltran** [comment]
Hi Nick, thanks for reporting this.

Are you looking at the develop branch?

We now have replaced the "characteristics" for "characteristicCategories" instead (see here: [assay_schema.json](https://github.com/ISA-tools/isa-api/blob/develop/isatools/schemas/isa_model_version_1_0_schemas/core/assay_schema.json)). I double-checked and the spelling should be fine now.

Many thanks
