### ISSUE TITLE
property "materials" in assay_schema.json is not correct

### ISSUE THREAD

**Issue by ntk73** [ISA-tools/isa-api#67]
I suppose that something is missing in the declaration of "materials" section.

 "materials": {
      "samples": {
        "type": "array",
        "items": {
          "$ref": "sample_schema.json#"
        }
      },
      "otherMaterials": {
        "type": "array",
        "items": {
          "$ref": "material_schema.json#"
        }
      }
    },

At least  "type" : "object", can be added. Also "samples" and "otherMaterials" should be declared as properties of the object "materials", so I suppose "properties" is missing as well.

**Comment by agbeltran** [comment]
Thanks - I will fix this (the schemas are validating, though - but it might be a problem with the validator)
