### ISSUE TITLE
ISA tab validator (Python version)

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#68]

**Comment by djcomlab** [comment]
Currently the ISA validator is already in the API (the Java version)

in: https://github.com/ISA-tools/isa-api/blob/develop/isatools/isatab.py

see function validate(isatab_dir, config_dir)

**Comment by agbeltran** [comment]
Yes, thanks. This issue intended to document that we need to make sure that the Java version works as expected (adding tests, etc) and/or consider alternatives. This is in view of Release 0.2. so we can discuss in the next meeting.

**Comment by djcomlab** [comment]
This feature should replace the Java validator in its entirety sine we need to better understand the validation rules (see #79), and improve the reporting of validation errors.

**Comment by djcomlab** [comment]
Merged to master, closing.
