### ISSUE TITLE
Integrate ISA API to use in IPython Notebook

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#69]
Interactive creation and use of ISA objects, requested by @proccaserra

**Comment by proccaserra** [comment]
this needs to be qualified: What does ipython/jupyter requires?
  https://jupyter-notebook.readthedocs.org/en/latest/

@djcomlab may have more info following the meeting in Sweden.

**Comment by eamonnmag** [comment]
You just need to install the api in the virtualenv etc. you are running the ipython notebook from and it'll be available for use.

**Comment by proccaserra** [comment]
thx Dr E! sounds straightforward

**Comment by djcomlab** [comment]
Yep, iPython is just an interactive tool, and notebooks are interactive-y documents. All we need to do is create a bunch of notebooks for our exemplars. Closing since we don't actually need to do anything more to make it work.
