### ISSUE TITLE
Specify validator rules

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#79]
related to #68

**Comment by djcomlab** [comment]
@proccaserra will dig out validation rules document that we can work on.

**Comment by djcomlab** [comment]
The validation rules for ISA tab aren't well defined, where much of the validation done by the Java validator is embedded in the code. We need to document the validation rules for ISA tab so we can get a new Python validator written (see #68) and also extract rules for ISA JSON (and model) validation (see #98).

**Comment by djcomlab** [comment]
https://docs.google.com/spreadsheets/d/1avWQy1eW0FApjOT5-UHOUUopi1-Mt1ehe4LntrKz5ok/edit?usp=sharing

**Comment by eamonnmag** [comment]
The rules are defined via the code here - https://github.com/ISA-tools/ISAvalidator-ISAconverter-BIImanager/tree/master/import_layer/src/main/java/org/isatools/isatab/isaconfigurator/validators

The code pretty much maps directly to the rules. There was a document that we created a long time ago to describe the various rules. But, I cannot find it.

**Comment by proccaserra** [comment]
thx @eamonnmag , was too trying to find that document, but I think we dropped it one the rules were implemented.

**Comment by djcomlab** [comment]
The rules (including how they map roughly to the Java rules in the old code - thanks @eamonnmag) are now in the rules spreadsheet linked above. Closing.
