### ISSUE TITLE
Installing isatools package from pip doesn't install dependencies

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#89]
I tried installing and using via my Pycharm the isatools package that is published on PyPI, and it installed fine but missed installing the dependencies. I expected that it should install all related dependencies as specified in the requirements.txt file when installing the package, but doesn't seem to.

* Create new Python project in Pycharm, configured interpreter to use a new virtual environment with Python 3.5
* Copy across the tests package only from the isa-api project
* Running test_isa_objects.py fails by not finding networkx; resolve by installing networkx
* Running test_isatab.py fails by not finding pandas; resolve by installing pandas
* Running test_isatab2cedar.py fails by not finding jsonschema; etc...

**Comment by eamonnmag** [comment]
You need to add install_requires to your setup.py file.
```

install_requires = ["biopy-isatab",
"jsonschema",
"pandas",
"networkx",
"behave",
"httpretty",
"sure",
"lxml",
"requests",
"coveralls"]
```

**Comment by djcomlab** [comment]
Just tested it, is fixed.

**Comment by agbeltran** [comment]
Great, tx. I tested on my end too. Thanks @eamonnmag !

**Comment by eamonnmag** [comment]
No problem :dancers:
