### ISSUE TITLE
Creation functionality for ISA v1

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#9]
Start creating individual objects

   - create sample
   - create set of samples with same characteristics
   - create study
   - create assay

**Comment by proccaserra** [comment]
see the following feature file:
https://github.com/ISA-tools/isa-api/blob/master/features/isa-material-batch-creation.feature

comment and raise flags if you identify blockers

**Comment by djcomlab** [comment]
@proccaserra For batches, we need distinct object (Source, Sample, Material) names right?

**Comment by djcomlab** [comment]
All model objects are there to be used to create individual objects.

Batch creation supported in the following utility functions:

* ```batch_set_attr(l=list(), attr=None, val=None)``` - batch set attributes for all objects in a list
* ```batch_create_assays(*args, n=1)``` - batch create n processes with inputs and outputs (simple patterns only)
* ```batch_create_materials(material=None, n=1)``` - batch create n material objects.

Closing as further work can be done on this when use cases are better defined, in next release.
