### ISSUE TITLE
isatab2json doesn't find schemas in PyPI distribution

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#90]
Actually, I found running the isatab2json tests (and through trying to use the Python package directly) that the conversion can't find the schemas in the package. Those directories might need to be package-ized and declared in the setup.py

This is the output when I try and run it from a Docker container:

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/site-packages/isatools/convert/../schemas/isa_model_version_1_0_schemas/core/investigation_schema.json'
```

**Comment by eamonnmag** [comment]
You have to add this. 
```
package_data={'isatools': ["schemas/*"]},
```

I don't think the * will capture all the subdirectories though. You might have to explicitly define each, so.

```
package_data={'isatools': ["schemas/*", "schema/cedar/*", ...]},
```

**Comment by djcomlab** [comment]
Thanks for the pointer (again) @eamonnmag! Fixed, closing.
