### ISSUE TITLE
Distribution package cannot find files needed for command line methods

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#93]
When installing the package in a new virtualenv and running a new test such as
`from isatools import isatab`
`isatab.validate('./TEST-ISA-charac-param-factor/',` `'./isaconfig-default_v2015-07-02/')`
the config.sh script is not found.

> Using source ISA Tab folder: ./TEST-ISA-charac-param-factor/
ISA configuration XML folder: ./isaconfig-default_v2015-07-02/
/Users/agbeltran/work-dev/cleanslate/venv/lib/python3.5/site-packages/isatools/convert/isa_line_commands/bin/lib/invoke.sh: line 12: /Users/agbeltran/work-dev/cleanslate/venv/lib/python3.5/site-packages/isatools/convert/isa_line_commands/bin/lib/../config.sh: No such file or directory
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> Returned 1

**Comment by djcomlab** [comment]
Fixed.
