### ISSUE TITLE
ISA mime types

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#96]
Could you tell if there are MIME types defined for ISA-TAb (and perhaps ISA-JSON)? 

I've found Apache Tika uses three MIME types for their ISA parser , i.e. `application/x-isatab-*`. Are these the ones to use?

**Comment by djcomlab** [comment]
I don't think this is something that has been defined by us - it's not something that is in the ISA tab v1.0 RC1 specification document. So it's interesting to hear that there is some MIME type definitions out there!

At the moment in the latest ISA API work and specifically the REST service that goes with it, we've been using `application/zip` for ISA tab archives that are zipped with each type of file inside and `application/json` for ISA JSON.

I see there's this project https://github.com/giuseppetotaro/ISATabParser that I looks like it has then been contributed back to Apache Tika (for reference see https://issues.apache.org/jira/browse/TIKA-1580).

Have you tried this parser yourself?

**Comment by djcomlab** [comment]
Hi Nina, just wondering if your question has been answered adequately? If so I will close this issue.

**Comment by vedina** [comment]
Hi David, 

For the mime types, `application/json` is less informative than `application/x-isa-tab` , as it does not tell what json schema is used.  You could consider smth like `application/isa+json` (analogy with [application/ld+json](https://en.wikipedia.org/wiki/JSON-LD).

You could close the issue, it was more an information request rather than an issue.
